### PR TITLE
Added functionality to ignore applications while show-desktop is trig…

### PR DESCRIPTION
**Pull request by ilyuha21st**
As described at #292, it is possible to add gui applications separated by comma to show-desktop-skip-list located at 'org/mate/marco/general'.  In this case 'show-desktop' functionality has not impact at all to each application in given list. Value passed to skip list can taken by 'xprop' application available on most linux desktop. Need to add to the list second value of WM_CLASS properties.

### CODE REVIEW

**Comment by raveit65** [comment]
@ilyuha21st 
Can you rebase the PR with master please, I'd like to going in review process.
There is a conflict with src/include/prefs.h

**Comment by ilyuha21st** [comment]
Current functionality is case insensible. Possibly better to make it sensible...

**Comment by raveit65** [comment]
hmm, merge isn't the same like git rebase, now we have a useless merge commit :-/

**Comment by raveit65** [comment]
Re-ordering the commit to the top in your branch with 'git rebase -i 40e26ed6d0e9ef84522ad0723f630bd7d796beec' doesn't work w/o editing prefs.h by hand.
Hope that this patch which is your commit on top of the git log is the same.
https://gist.github.com/raveit65/817f1ea8918c4e4f5a353aa7a7136fce
See different in prefs.h

**Comment by raveit65** [comment]
Beside from the git problem your PR works great :-)
@monsta 
@stefano-k 
Can you please do a code review too.

**Comment by ilyuha21st** [comment]
I have merged manually as github allows via WBM interface (just inserted one line code, and removed git conflict notations). Bit unexpected is no rebase is performed.

**Comment by raveit65** [comment]
It works also with using crtl+alt+D to show and focus the desktop.

**Comment by raveit65** [comment]
I tested it several days with kaffeine and it works well. I will merge it.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/marco/commit/238373df58d4ba275b7aead36f4d47971fbed18d
Thank you

**Pull request closed without merging**
