### PR TITLE
tile preview: invalidate window before showing

### PR DESCRIPTION
**Pull request by dnk**
fix for https://github.com/mate-desktop/marco/issues/158

### CODE REVIEW

**Comment by infirit** [comment]
I can still reproduce this after applying this patch. What I do is move it from side to side multiple times, it sometimes takes a few tries but eventually I get a flicker.

**Comment by NiceandGently** [comment]
I can't reproduce this glitches with mate gtk2 and gtk3 builds in fedora 22 (mate-1.10).
Note, i use this PR and the ' adding keybindings for tiling' PR, since several month for mate-1.8/10 builds for official fedora, and have no reports about it.

**Comment by flexiondotorg** [comment]
Thanks for your contribution.

**Comment by monsta** [comment]
@flexiondotorg: I guess https://github.com/mate-desktop/marco/issues/158 (and LP report that's mentioned there) can be closed now?

**Pull request merged**
