### PR TITLE
compositor-xrender: avoid deprecated 'gdk_error_trap_push/pop'

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by muktupavels** [comment]
Why not `meta_error_trap_push` and `meta_error_trap_pop_with_return`?

**Comment by sc0w** [comment]
@muktupavels 

because that functions have deprecated 'gdk_error_trap_push' and deprecated 'gdk_error_trap_pop'

https://github.com/mate-desktop/marco/blob/master/src/core/errors.c#L34

https://github.com/mate-desktop/marco/blob/master/src/core/errors.c#L53

**Comment by muktupavels** [comment]
Why would that be problem?

**Comment by sc0w** [comment]
In the fixes of deprecated functions I like to respect the original style, the deprecated function is here and I fixed it here

**Comment by muktupavels** [comment]
I understand, but why do this to redo that later? That is only place where gdk functions are used directly if we don't count `errors.c`. Also it seems that it is only reason why `gtk/gtk.h` and `gdk/gdk.h` is included here...

**Comment by raveit65** [comment]
> Why not `meta_error_trap_push` and `meta_error_trap_pop_with_return`?

Why?
I see no reason to replace a deprecated function with a function which has deprecated elements.

**Comment by muktupavels** [comment]
Do you know why these functions was deprecated? Do you know why these functions are needed?

I am just suggesting change that would be better in my opinion. Is not that point of reviews? Spotting mistakes, suggesting better solutions? Otherwise what is point of review for this? Change is simple enough and could have been directly pushed to master...

All codebase use `meta_error_trap_*` functions, I would say that these gdk functions should never been added there in first place (that was done already in metacity).

Doing that code would follow same style and you will be able to remove now unneeded includes. Not my suggestion nor change in this merge request change functionality...

**Comment by raveit65** [comment]
Please do a PR if you know it better than all other people here ;)

**Pull request merged**
