### PR TITLE
Backport changes to fix segfault

### LINKED ISSUE #559: Segmentation fault in meta_frame_calc_borders
#### Expected behaviour
No segfault

#### Actual behaviour
Segfault

#### Steps to reproduce the behaviour
I haven't found a way to always trigger a segfault, but what I did was execute `marco --replace --no-force-fullscreen` and bring guake to foreground using a shortcut.
The crash happened twice until now in about 2-3 hours after executing the command.
Side note: I am running maximus to remove the decoration of windows when in fullscreen mode.
I have both coredumps of the crash but I'm not sure which privacy related data is in there.
Here is the systemd-coredump message for start:
```
Sep 29 00:36:37 tarvos systemd-coredump[153768]: Process 146925 (marco) of user 1001 dumped core.
                                                 
                                                 Stack trace of thread 146925:
                                                 #0  0x00007f3c57cfb45a meta_frame_calc_borders (libmarco-private.so.2)
                                                 #1  0x00007f3c57ce9f01 n/a (libmarco-private.so.2)
                                                 #2  0x00007f3c57cebed5 n/a (libmarco-private.so.2)
                                                 #3  0x00007f3c57ceced2 n/a (libmarco-private.so.2)
                                                 #4  0x00007f3c57cf5c41 n/a (libmarco-private.so.2)
                                                 #5  0x00007f3c57d3f815 n/a (libmarco-private.so.2)
                                                 #6  0x00007f3c571fa58f n/a (libgdk-3.so.0)
                                                 #7  0x00007f3c57204b94 n/a (libgdk-3.so.0)
                                                 #8  0x00007f3c57259ceb gdk_display_get_event (libgdk-3.so.0)
                                                 #9  0x00007f3c572048f4 n/a (libgdk-3.so.0)
                                                 #10 0x00007f3c57c083ae g_main_context_dispatch (libglib-2.0.so.0)
                                                 #11 0x00007f3c57c0a1c1 n/a (libglib-2.0.so.0)
                                                 #12 0x00007f3c57c0b0d3 g_main_loop_run (libglib-2.0.so.0)
                                                 #13 0x0000556121fe18c9 main (marco)
                                                 #14 0x00007f3c579e0ee3 __libc_start_main (libc.so.6)
                                                 #15 0x0000556121fe1d1e n/a (marco)
                                                 
                                                 Stack trace of thread 146928:
                                                 #0  0x00007f3c57aab667 __poll (libc.so.6)
                                                 #1  0x00007f3c57c0a130 n/a (libglib-2.0.so.0)
                                                 #2  0x00007f3c57c0a201 g_main_context_iteration (libglib-2.0.so.0)
                                                 #3  0x00007f3c57d82e5e n/a (libdconfsettings.so)
                                                 #4  0x00007f3c57be6bc1 n/a (libglib-2.0.so.0)
                                                 #5  0x00007f3c57b8657f start_thread (libpthread.so.0)
                                                 #6  0x00007f3c57ab60e3 __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 146927:
                                                 #0  0x00007f3c57aab667 __poll (libc.so.6)
                                                 #1  0x00007f3c57c0a130 n/a (libglib-2.0.so.0)
                                                 #2  0x00007f3c57c0b0d3 g_main_loop_run (libglib-2.0.so.0)
                                                 #3  0x00007f3c56e99b18 n/a (libgio-2.0.so.0)
                                                 #4  0x00007f3c57be6bc1 n/a (libglib-2.0.so.0)
                                                 #5  0x00007f3c57b8657f start_thread (libpthread.so.0)
                                                 #6  0x00007f3c57ab60e3 __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 146926:
                                                 #0  0x00007f3c57aab667 __poll (libc.so.6)
                                                 #1  0x00007f3c57c0a130 n/a (libglib-2.0.so.0)
                                                 #2  0x00007f3c57c0a201 g_main_context_iteration (libglib-2.0.so.0)
                                                 #3  0x00007f3c57c0a252 n/a (libglib-2.0.so.0)
                                                 #4  0x00007f3c57be6bc1 n/a (libglib-2.0.so.0)
                                                 #5  0x00007f3c57b8657f start_thread (libpthread.so.0)
                                                 #6  0x00007f3c57ab60e3 __clone (libc.so.6)
```

And here is some more:
```
(gdb) frame 0
#0  0x00007f3c57cfb45a in meta_frame_calc_borders () from /usr/lib/libmarco-private.so.2
(gdb) info frame
Stack level 0, frame at 0x7ffc6cb62a00:
 rip = 0x7f3c57cfb45a in meta_frame_calc_borders; saved rip = 0x7f3c57ce9f01
 called by frame at 0x7ffc6cb62b30
 Arglist at 0x7ffc6cb629f0, args: 
 Locals at 0x7ffc6cb629f0, Previous frame's sp is 0x7ffc6cb62a00
 Saved registers:
  rip at 0x7ffc6cb629f8
(gdb) x/10x $sp
0x7ffc6cb629f8:	0x57ce9f01	0x00007f3c	0x2334cfc0	0x00005561
0x7ffc6cb62a08:	0x56a57558	0x00007f3c	0x6cb62a70	0x00007ffc
0x7ffc6cb62a18:	0x00000000	0x00000001
```

#### MATE general version
1.22.2

#### Package version
1.22.2-1

#### Linux Distribution
Arch Linux

#### Link to downstream report of your Distribution
n/a

### PR DESCRIPTION
**Pull request by vkareh**
Possibly fixes #559

### CODE REVIEW

**Comment by muktupavels** [comment]
How this can fix mentioned crash?

**Comment by raveit65** [comment]
I will test it soon because i have a lot bug reports in fedora since December last year with `meta_frame_calc_borders`.
See my depressing bug list https://apps.fedoraproject.org/packages/marco/bugs
This isn't normal. Normally i have max. 2 or 3 open bugreports with marco.
This means we have an issue since marco-1.22.4 or another low-level application in the background has been changed.

**Comment by vkareh** [comment]
> How this can fix mentioned crash?

I don't know if it will, but I based it on this comment: https://github.com/mate-desktop/marco/issues/559#issuecomment-583358792

I personally was not able to reproduce the issue, so I backported metacity code that updates the code referenced, which includes checks so that it doesn't calculate the visible region if there's no window region.

**Comment by sc0w** [comment]
new warnings in the logs:

```
ui/frames.c: In function 'meta_frames_get_mask':
ui/frames.c:2457:35: warning: unused parameter 'width' [-Wunused-parameter]
 2457 |                       guint       width,
      |                       ~~~~~~~~~~~~^~~~~
ui/frames.c:2458:35: warning: unused parameter 'height' [-Wunused-parameter]
 2458 |                       guint       height,
      |                       ~~~~~~~~~~~~^~~~~~

compositor/compositor-xrender.c: In function 'get_window_mask':
compositor/compositor-xrender.c:1401:5: warning: implicit declaration of function 'meta_frame_get_mask'; did you mean 'meta_frame_get_xwindow'? [-Wimplicit-function-declaration]
 1401 |     meta_frame_get_mask (frame, cr);
      |     ^~~~~~~~~~~~~~~~~~~
      |     meta_frame_get_xwindow
```

**Comment by muktupavels** [comment]
> I personally was not able to reproduce the issue, so I backported metacity code that updates the code referenced, which includes checks so that it doesn't calculate the visible region if there's no window region.

Why not just add needed checks if you think that might be the problem?

**Comment by raveit65** [comment]
I have the PR installed and i don't see problems in a quick test.
As i don't know what it should fix and i never could reproduce my fedora bug reports with sefaults of
marco: meta_frame_calc_borders(): marco killed by SIGSEGV
marco: meta_frame_get_frame_bounds(): marco killed by SIGSEGV 
marco: INT_cairo_region_num_rectangles(): marco killed by SIGSEGV
see https://apps.fedoraproject.org/packages/marco/bugs
, i can only test if it runs several days fine.

**Comment by muktupavels** [comment]
Did not you introduce this regression in 1.22 with 1.22.4 release? The only relevant commit might be https://github.com/mate-desktop/marco/commit/baef3d7f25bbd4665ecced218be3b4e97c4d8a02...

Write small app that quickly toggles decorations and/or hides/shows window. Sooner or later you will get crash...

**Comment by raveit65** [comment]
Me ??
Which regression did i introduced with 1.22.4 release?
Reverting https://github.com/mate-desktop/marco/commit/df56628979abc17474b001c58c28c6f3637ada9d was a bug fix for
https://github.com/mate-desktop/marco/issues/560

**Comment by muktupavels** [comment]
No. With you I did not mean you personally but project/team. :)

All bugs started with 1.22.4, no? At least quickly looking I did not see such crash/bug reported for 1.22.3... Just because it fixed something else does not mean it did not introduce this regression.

And if I am right, none of these commit will magically fix this crash.

**Comment by vkareh** [comment]
Wait a second, this is a regression from 1.22.4, not 1.22.3!? :man_facepalming: 

I thought this was introduced in 1.22.3, with #503 being the most likely culprit, and so I've been going crazy trying to backport commits that touch the specific area of the code mentioned by the crash reports, since I'm coding in the dark here (haven't been able to reproduce the issue at all).

If this is a 1.22.4 issue, then I agree with @muktupavels, this must be due to baef3d7f25bbd4665ecced218be3b4e97c4d8a02...

That said, df56628979abc17474b001c58c28c6f3637ada9d did cause a bunch of issues with window focus. Any help regarding what the solution might be would be appreciated...

I'll play around some more with fixing df56628979abc17474b001c58c28c6f3637ada9d...

**Comment by muktupavels** [comment]
From what I see it did start with #503... First you had regression from bcd38af (df566289 backported), then you reverted that to fix one regression introducing other (this one).

**Comment by raveit65** [comment]
@muktupavels 
I recall that you said to  me at irc channel that https://github.com/mate-desktop/marco/commit/df56628979abc17474b001c58c28c6f3637ada9d can't be used for marco bcause something is missing in marco, when i reverted this commit the first time for fixing https://github.com/mate-desktop/marco/issues/251 in 10 May 2017.

But honestly i forgot what you did say after 3 years :)

**Comment by vkareh** [comment]
omg, looking at https://github.com/mate-desktop/marco/commit/38940edf002a137a7e6c041462d334967fd9ff29 made me laugh... so this has been an issue for 3 years and I just reintroduced it... so after reverting, for a second time, that commit, turns out that the new issue is then introduced by #503... okay... 

So, it doesn't solve the issue that I'm still coding in the dark, so I'll just keep testing the backports in this pull request to make sure I don't see any new regressions, but until someone else can reproduce the issue and then have it fixed by this commit, then I have no confirmation... I've never seen the issue in #559 myself

**Comment by raveit65** [comment]
Same as me, i never noticed https://github.com/mate-desktop/marco/issues/559 or the others from fedora bug list for myself.
So, i am not really sure if the fedora reports are not caused by another low-level program.

**Comment by muktupavels** [comment]
As I said write test app.

I don't remember details and a lot has changed. I think problem is that compositor is painting or processing event for window that core has already destroyed/freed.

Most stacktraces I saw crashed in border_size(). Before invisible borders this function did not access/use MetaWindow. Then in few stacktraces crash starts in process_configure_notify() -> win_extents(). Again looks like before invisible borders it did not access MetaWindow.

**Comment by vkareh** [comment]
okay, this no longer works as of the latest commits in marco... all windows are now getting an ugly black background around them where the invisible borders should be.

I'll try to write something to reproduce the issue and then address... closing for now :(

**Comment by rcaridade145** [comment]
If the pixmap is rgba black means we are considering (0,0,0,1).  Wonder where we are defining that. Should be all 0

**Comment by muktupavels** [comment]
Why do you think there is alpha? Client windows have mostly 24-bit depth, and frames are created with same visual as client window - https://github.com/mate-desktop/marco/blob/master/src/core/frame.c#L96.

**Comment by lukefromdc** [comment]
I'm wondering if  https://github.com/mate-desktop/marco/pull/503 (invisible borders) needed some underlying commit applied during the 1.23 development sequence that 1.22 did not get in order to work properly?

**Comment by muktupavels** [comment]
Why do you think it is fixed/works with master?

**Comment by rcaridade145** [comment]
@muktupavels I read about transparency and transparency on some of metacity comments and was under that impression.
I have been debugging this issue (using the backtrace from https://github.com/mate-desktop/marco/issues/559#issuecomment-565549185) and i have come to some ideas what may be causing this. From that post it seems also there are two possible crash reasons :

-  At meta_frame_get_frame_bounds

- At cairo_region_to_xserver_region

For the first case one of the  frame elements must be null 

`frame->window->screen->ui,
                                   frame->xwindow,
                                   frame->rect.width,
                                   frame->rect.height`

so most likely 

`if(frame->rect && frame->window && frame->window->screen && frame->window->screen->ui)  {
	return meta_ui_get_frame_bounds (frame->window->screen->ui,
                                   frame->xwindow,
                                   frame->rect.width,
                                   frame->rect.height);
  }
  return NULL;`

will not allow it to happen, no?

The second issue must be related to what was solved by this commit https://gitlab.gnome.org/GNOME/metacity/blob/7ba07cfe617037b442d370b9d7e3519e3065e935/src/compositor/meta-compositor-xrender.c . However on border_size the code will never be called due to the return NULL introduced above.

@vkareh On a transparent terminal, for instance, with this pull request do the transparency effects work or it is black?.

**Comment by muktupavels** [comment]
From what I remember problem is freed window used in compositor.

@vkareh was able to crash marco (from IRC):
> managed to crash marco by keeping Super+RightArrow pressed on a terminal window, cycling through tiling as fast as my keyboard repeat speed will allow

Don't now how often he can get crash, but maybe try it? If it crashes often enough then you can verify your ideas.

**Comment by rcaridade145** [comment]
@vkareh @muktupavels OT: Need to be more on IRC (don't know channel and that stuff though) lol

**Comment by raveit65** [comment]
I got a segfault today see https://github.com/mate-desktop/marco/issues/596
I found the coredumps under /var/lib/systemd/coredump/

**Comment by raveit65** [comment]
Found another coredump from last Friday, see https://github.com/mate-desktop/marco/issues/598

**Pull request closed without merging**
