### PR TITLE
Multimonitor keybinds

### LINKED ISSUE #320: Multi-monitor keyboard shortcuts [$25]
Currently (as of 1.12.1, not sure about newer versions), there aren't any keybaord shortcuts that can be set to move the current window to the next/previous monitor. I'm constantly forced to use my mouse in order to move the window.

This is something I'm really missing from other window managers, and multi-monitor setups have become very commonplace nowadays (compared to the gnome2 days), so I'd really like to see this.

<bountysource-plugin>

---
There is a **[$25 open bounty](https://www.bountysource.com/issues/45282538-multi-monitor-keyboard-shortcuts?utm_campaign=plugin&utm_content=tracker%2F841233&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F841233&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ozeidan**
Hi,

I implemented proper keybinds for moving windows between monitors that work with tiled/maximized/fullscreen windows.

Please test it and sorry for the PR spam :)

Closes #320

### CODE REVIEW

**Comment by jhasse** [comment]
How can  I assign those keybindings when running a local marco build via `./src/marco --replace`?

**Comment by ozeidan** [comment]
@jhasse @lukefromdc you have to recompile the gschema: I usually do this by copying the file `src/org.mate.marco.gschema.xml` into `/usr/share/glib-2.0/schemas` and then `running lib-compile-schemas /usr/share/glib-2.0/schemas`. Then the options `move-to-monitor-(n|e|s|w)` should show up in dconf-editor at path `/org/mate/marco/window-keybindings/`.

**Comment by ozeidan** [comment]
Also, I still found an issue with this implementation: When moving a firefox window that is either fullscreen or maximized to another monitor, it jumps right back. Can you guys reproduce that?

**Comment by lukefromdc** [comment]
I did recompile the schema, and the default disabled keybindings showed up in dconf-editor, but when I tried things like <ALT>F12 or <ALT>m they had no effect. I'm not an expert on this, my workflow is mostly mouse driven with few keybindings used and only the ctrl-alt-backspace changed back to its old binding to kill the X server/

**Comment by ozeidan** [comment]
@lukefromdc west means right to left. Try placing the window on the right monitor and then pressing the key.

As a side note: currently I am using a function that already existed to determine the neighbour in the according direction. This works fairly well, though the current algorithm stops checking once it has found a monitor in the given direction. This means that if you have two monitors on a side of the current monitor, one the one which was registered first will always be chosen. Maybe I should improve this logic by checking which of those the screens is closer vertically (in the cases of move-to-monitor-(w|e)). What do you guys think?

**Comment by raveit65** [comment]
> Also, I still found an issue with this implementation: When moving a firefox window that is either fullscreen or maximized to another monitor, it jumps right back. Can you guys reproduce that?

Yes, it's reproducible here, but only with firefox.  I tested this with chrome, vlc, mate-terminal and i don't see this issue.
firefox problem?

>  Maybe I should improve this logic by checking which of those the screens is closer vertically (in the cases of move-to-monitor-(w|e)). What do you guys think?

I don't think that i can test a 3 monitor setup. There is a report somewhere that it is impossible to setup 3 Monitors with mate-display-properties.
And i don't have 2 external monitors/tvs in one room ;-)
But go ahead if you can test it. I am sure there are some ppl who use 3 or more monitors.

Setting up the keybindings is working with both tools here, mate-keybinding-properties and dconf-editor.
Only keys with more than 2 levels are critical. An example for move-to-monitor-north with a vertical monitor setup.
```
crtl+Shift+Alt+KP_Up    --> works
crtl+Shift+Alt+u             --> works
crtl+Shift+Alt+8             --> don't work
```
The last one is impposible to setup with german keyboard layout and mate-keybinding-properties and move-to-monitor-north function doesn't work.
The result is always
```
crtl+Shift+Alt+[
```
With german layout you need *altgr* key to type *[* 

(I hope this is understandable because of my poor english)

I think such weirdness is more a general problem than a problem with your PR.

**Comment by raveit65** [comment]
@lukefromdc 
Could you solve to setup some working keys?
@ozeidan 
Beside from firefox, do you think this is ready to go?
We want to freeze MATE in a few days for releasing 1.20 end of this month, than only bugfixes are allowed to merge.

**Comment by ozeidan** [comment]
The only other issue I found was, when you have a fullscreen window on a monitor and move a window to that monitor, the moved window gets placed behind the fullscreen window. I'll try to fix this today or tomorrow, otherwise I think it's ready to merge.

**Comment by raveit65** [comment]
Ok, but isn't a fullscreen-window not always in the foreground?
I never saw another window ontop of a fullscreen-window.
Or do i miss something?

**Comment by monsta** [comment]
Looks like https://github.com/mate-desktop/marco/pull/371/commits/15da872d741a683ba57d38ed08f6c42608447f14 might affect some existing features.

**Comment by monsta** [comment]
> When moving a firefox window that is either fullscreen or maximized to another monitor, it jumps right back.

I'm not surprised at all. We already have https://github.com/mate-desktop/marco/issues/28. Maybe Mozilla needs to learn to use GTK+?

**Comment by lukefromdc** [comment]
I have zero experience setting up custom keybindings, and also would need to be damned sure they got reverted. Not sure if I will have time for this one today.

**Comment by lukefromdc** [comment]
I have no issue with merging this

**Comment by ozeidan** [comment]
@raveit65 when a window is fullscreen, you still can alt-tab to get another window in front of it. So I think if you move a window to that monitor it should be on top, just because it's really confusing otherwise. 

@monsta I changed the parameter from FALSE to TRUE because I found some bug that this fixes. As I remember it this only changes the behavior of the move-to-X keybinds

**Comment by raveit65** [comment]
> when a window is fullscreen, you still can alt-tab to get another window in front of it. So I think if you move a window to that monitor it should be on top, just because it's really confusing otherwise.

Indeed, i didn't known that, btw. i never tried this ;-)
The result is that the panel, in my case top and bottom panel are on top of the fullsreen-window,
which looks very scary if you use a transparent panel.
I don't think i will use that for productivity :-)

But, i think that both arguments are legitim , for me the alt-tab function is a special case with a fullscreen window.
Any way, i don't care much about if this is an issue or not.

**Comment by monsta** [comment]
What is that bug? Is it in this PR or in some existing feature?

**Comment by raveit65** [comment]
@ozeidan 
Today is the last day for merging before feature freeze for 1.20.
Otherwise  this new feature goes into next development cycle (1 year)
Personal i can live with the fullscreen-window issue for the moment.
If i merge the PR today you can fix it later.

**Comment by ozeidan** [comment]
@monsta I believe the bug was, when moving a window with move-to-side-X so
that it switches to another monitor, the user_rect would stay on the old
monitor (because that parameter was false). Then fullscreening it, it would
pop up back on the old monitor. I noticed this because the keybindings
introduced in this PR also had this issue initially. The other change is
something that I forgot to change in a previous PR, although it doesn't
change any behavior. It's just an inconsistency in the code which came to
be because if the corner tiling system. In hindsight I shouldn't have made
these undocumented changes, sorry for that.

@raveit65 I think the PR is good to go for now. I'll try to look at the
other bug this week, but I don't think it's very critical

raveit65 <notifications@github.com> schrieb am Mo., 15. Jan. 2018, 16:38:

**Comment by raveit65** [comment]
Thanks.

**Comment by csarmendariz** [comment]
Hi, 

Sorry because I'm pretty new so the question can be a bit silly...
I would love to be able to move windows between monitors, I think is the only functionality I'm missing in marco.
However I cannot find how to activate the keybinds you guys are talking about here... not sure if I have an old version of marco without this functionality activated.
I'm running ubuntu mate 16.04, is there a way I could activate a keyboard shortcut to send window to the other monitor?
Thanks and sorry if this is not the place to ask.

**Comment by raveit65** [comment]
You need Mate-1.20 (ubuntu.18.04)

**Pull request merged**
