### PR TITLE
Add invisible resize borders

### PR DESCRIPTION
**Pull request by vkareh**
This is mostly a bunch of backports, hacks, and undos from years past. The goal is to provide invisible resize borders. I had to refactor all the HiDPI handling stuff and use metacity's code to avoid graphical glitches with the window shadows...

Please **do not merge** this, as I would prefer to do this differently.

### CODE REVIEW

**Comment by raveit65** [comment]
Really nice work and it seems to be working :)
Is it possible that everything is a bit smaller like before, after the refactoring of HIDPI scaling.
I noticed that the top decoration is 1or 2 mm smaller.
And menta decoration has weird white ears at top corners. There i something in the background which doesn't draw a radius.

**Comment by vkareh** [comment]
Yes, the scaling stuff I don't like, and yeah I can see the corner issues on Menta.

I would much rather not have that last commit, but it's the only way I've found to enable the invisible borders without a weird shadow around HiDPI windows... I might try again without that last commit and fixing it directly in the compositor, but please let me know if you notice any memory or instability issues.

**Comment by raveit65** [comment]
I think that the top decoration looks a bit smaller isn't a problem because after half an hour it looks normal again;)
But themes are looking much better after i reduced border width in frame geometry. :)
```
    <distance name="left_width" value="1" />
    <distance name="right_width" value="1" />
    <distance name="bottom_height" value="1" />
```

**Comment by raveit65** [comment]
I could eliminate the weird ears of the corners.
```
- <frame_geometry name="normal" title_scale="medium" rounded_top_left="4" rounded_top_right="4">
+ <frame_geometry name="normal" title_scale="medium" rounded_top_left="8" rounded_top_right="8">
```
Same for frame geometry `normal_unfocused`.
No idea why this needs to be done but it helps. :)

But the context-menu from title-decoration is really too small with HIDPI.
Looks like you introduced a metacity bug.
You had fixed than already in marco ;)

**Comment by raveit65** [comment]
Hmm, marco can crash if i press the close button in decoration.
```
[rave@mother ~]$ marco --replace
Window manager warning: Log level 6: ../glib/gmem.c:334: overflow allocating 18446744073367658512*8 bytes
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

**Comment by vkareh** [comment]
Okay, I was able to reproduce, but not consistently. I'll look into it.

Thanks for testing this! :)

**Comment by sc0w** [comment]
New clang warning in this PR:

```
ui/frames.c:689:69: warning: Access to field 'xwindow' results in a dereference of a null pointer (loaded from variable 'frame')
  meta_core_get (GDK_DISPLAY_XDISPLAY (gdk_display_get_default ()), frame->xwindow,
                                                                    ^~~~~~~~~~~~~~
```

**Comment by raveit65** [comment]
Now i tried to click of a button of a confirmation dialog of caja.
But i have a stacktrace.
```
[New Thread 0x7fffe3fff700 (LWP 3304)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
<cut>
warning: Loadable section ".note.gnu.property" outside of ELF segments
marco: xcb_conn.c:303: write_vec: Zusicherung »n == 0« nicht erfüllt.

Thread 1 "marco" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) thread apply all bt full

<cut>

Thread 1 (Thread 0x7ffff60a0a80 (LWP 3298)):
#0  0x00007ffff7c40eb5 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 140737350479297, 4222451712, 93824994515920, 93824994515920, 93824994515920, 93824994515920, 93824994515993, 93824994516020, 93824994515920, 93824994516020, 0, 0, 0, 0, 0}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff7c2b895 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x555555781bd0, sa_sigaction = 0x555555781bd0}, sa_mask = {__val = {0, 140737351818336, 73, 0, 0, 0, 21474836480, 140737488342752, 140733193388034, 93824992339088, 93824992339088, 0, 5338959443903848192, 140737351580528, 140736987504640, 140737103422558}}, sa_flags = -160927744, sa_restorer = 0x12f}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff7c2b769 in __assert_fail_base (fmt=0x7fffe90e645e "%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n%n", assertion=0x7ffff668701d "n == 0", file=0x7ffff6687000 "xcb_conn.c", line=303, function=<optimized out>) at assert.c:92
        str = 0x555555781bd0 ""
        total = 4096
#3  0x00007ffff7c395b6 in __GI___assert_fail (assertion=assertion@entry=0x7ffff668701d "n == 0", file=file@entry=0x7ffff6687000 "xcb_conn.c", line=line@entry=303, function=function@entry=0x7ffff6687040 <__PRETTY_FUNCTION__.11475> "write_vec") at assert.c:101
#4  0x00007ffff667469e in write_vec (count=0x7fffffffd134, vector=0x7fffffffd138, c=0x555555579410) at xcb_conn.c:303
        n = 1431685388
        __PRETTY_FUNCTION__ = "write_vec"
        ret = <optimized out>
        fd = {fd = 6, events = 5, revents = 5}
#5  0x00007ffff667469e in _xcb_conn_wait (c=c@entry=0x555555579410, cond=cond@entry=0x55555557a538, vector=vector@entry=0x7fffffffd138, count=count@entry=0x7fffffffd134) at xcb_conn.c:522
        ret = <optimized out>
        fd = {fd = 6, events = 5, revents = 5}
#6  0x00007ffff66749f9 in _xcb_out_send (c=c@entry=0x555555579410, vector=<optimized out>, vector@entry=0x7fffffffd1c0, count=<optimized out>, count@entry=3) at xcb_out.c:464
        ret = 1
#7  0x00007ffff6674a98 in xcb_writev (c=c@entry=0x555555579410, vector=vector@entry=0x7fffffffd1c0, count=count@entry=3, requests=requests@entry=261) at xcb_out.c:412
        ret = <optimized out>
#8  0x00007ffff6e41b9e in _XSend (dpy=dpy@entry=0x555555577090, data=data@entry=0x7ffd2d527010 "", size=size@entry=11453431936) at xcb_io.c:499
        dummy_request = {reqType = 0 '\000', data = 0 '\000', length = 0}
        pad = "\000\000"
        vec = {{iov_base = 0x55555557f5b4, iov_len = 0}, {iov_base = 0x7ffcd7fff090, iov_len = 12884901888}, {iov_base = 0x7ffff6eb4aac <pad>, iov_len = 0}}
        requests = 261
        dpy_request = <optimized out>
        ext = 0x0
        c = <optimized out>
#9  0x00007ffff6fa9fcc in XFixesCreateRegion (dpy=dpy@entry=0x555555577090, rectangles=rectangles@entry=0x7ffd2d527010, nrectangles=nrectangles@entry=1431678992) at Region.c:46
        info = <optimized out>
        req = <optimized out>
        len = 11453431936
        region = 76519934
#10 0x00007ffff7f224e8 in cairo_region_to_xserver_region (xdisplay=xdisplay@entry=0x555555577090, region=0x55555582f350) at compositor/compositor-xrender.c:628
        n_rects = 1431678992
        i = <optimized out>
        rects = 0x7ffd2d527010
        xregion = <optimized out>
#11 0x00007ffff7f251d8 in get_visible_region (cw=0x5555557ba600) at compositor/compositor-xrender.c:1259
        visible = <optimized out>
        tmp = <optimized out>
        display = <optimized out>
        xdisplay = 0x555555577090
        region = 76519933
        xdisplay = 0x555555577090
        last = 0x5555557c9940 = {0x5555557ba600, 0x5555558331c0, 0x5555558fa400, 0x5555557ff600, 0x55555578b800, 0x555555792550, 0x55555578fe90, 0x55555578cd50, 0x55555568a700, 0x5555555d6b80, 0x555555792010, 0x555555740de0, 0x555555759f60, 0x5555557161a0, 0x555555715fa0, 0x555555715be0, 0x5555556ac270, 0x5555556e7600, 0x5555556f3380}
        paint_region = 76519907
        display = 0x5555556613b0
        info = 0x5555556fd470
        index = 0x5555557c9940 = {0x5555557ba600, 0x5555558331c0, 0x5555558fa400, 0x5555557ff600, 0x55555578b800, 0x555555792550, 0x55555578fe90, 0x55555578cd50, 0x55555568a700, 0x5555555d6b80, 0x555555792010, 0x555555740de0, 0x555555759f60, 0x5555557161a0, 0x555555715fa0, 0x555555715be0, 0x5555556ac270, 0x5555556e7600, 0x5555556f3380}
        screen_width = 5760
        screen_height = 2160
        cw = 0x5555557ba600
        desktop_region = 0
        info = <optimized out>
        display = <optimized out>
        xdisplay = <optimized out>
        screen_width = 5760
        screen_height = 2160
#12 0x00007ffff7f251d8 in paint_windows (region=76519876, root_pixmap=<optimized out>, root_buffer=<optimized out>, windows=<optimized out>, screen=0x5555555aa9e0) at compositor/compositor-xrender.c:1615
        xdisplay = 0x555555577090
        last = 0x5555557c9940 = {0x5555557ba600, 0x5555558331c0, 0x5555558fa400, 0x5555557ff600, 0x55555578b800, 0x555555792550, 0x55555578fe90, 0x55555578cd50, 0x55555568a700, 0x5555555d6b80, 0x555555792010, 0x555555740de0, 0x555555759f60, 0x5555557161a0, 0x555555715fa0, 0x555555715be0, 0x5555556ac270, 0x5555556e7600,
        paint_region = 76519907
        display = 0x5555556613b0
        info = 0x5555556fd470
        index = 0x5555557c9940 = {0x5555557ba600, 0x5555558331c0, 0x5555558fa400, 0x5555557ff600, 0x55555578b800, 0x555555792550, 0x55555578fe90, 0x55555578cd50, 0x55555568a700, 0x5555555d6b80, 0x555555792010, 0x555555740de0, 0x555555759f60, 0x5555557161a0, 0x555555715fa0, 0x555555715be0, 0x5555556ac270, 0x5555556e7600, 0x5555556f3380}
        screen_width = 5760
        screen_height = 2160
        cw = 0x5555557ba600
        desktop_region = 0
        info = <optimized out>
        display = <optimized out>
        xdisplay = <optimized out>
        screen_width = 5760
        screen_height = 2160
#13 0x00007ffff7f251d8 in paint_all (screen=screen@entry=0x5555555aa9e0, region=region@entry=76519876, b=<optimized out>) at compositor/compositor-xrender.c:1791
        info = <optimized out>
        display = <optimized out>
        xdisplay = <optimized out>
        screen_width = 5760
        screen_height = 2160
#14 0x00007ffff7f25ffe in repair_screen (screen=screen@entry=0x5555555aa9e0) at compositor/compositor-xrender.c:1818
        damage = 76519876
        info = 0x5555556fd470
        display = 0x5555556613b0
        xdisplay = 0x555555577090
        __FUNCTION__ = "repair_screen"
#15 0x00007ffff7f27649 in xrender_present_complete (ce=<optimized out>, screen=0x5555555aa9e0) at compositor/compositor-xrender.c:2945
        info = <optimized out>
        ce = <optimized out>
        screen = 0x5555555aa9e0
        ge = 0x7fffffffd780
        xdisplay = 0x555555577090
#16 0x00007ffff7f27649 in process_generic (compositor=0x5555555f2000, compositor=0x5555555f2000, event=0x7fffffffd780) at compositor/compositor-xrender.c:2969
        ce = <optimized out>
        screen = 0x5555555aa9e0
        ge = 0x7fffffffd780
        xdisplay = 0x555555577090
#17 0x00007ffff7f27649 in xrender_process_event (compositor=0x5555555f2000, event=0x7fffffffd780, window=<optimized out>) at compositor/compositor-xrender.c:3339
#18 0x00007ffff7f2ff7a in event_callback (event=0x7fffffffd780, data=0x5555556613b0) at core/display.c:2614
        window = 0x0
        property_for_window = <optimized out>
        display = 0x5555556613b0
        modified = <optimized out>
        frame_was_receiver = <optimized out>
        filter_out_event = 0
#19 0x00007ffff7f78569 in filter_func (xevent=0x7fffffffd780, event=<optimized out>, data=<optimized out>) at ui/ui.c:228
        __FUNCTION__ = "filter_func"
#20 0x00007ffff744ab8f in gdk_event_apply_filters (xevent=xevent@entry=0x7fffffffd780, event=event@entry=0x5555555a29e0, window=window@entry=0x0) at gdkeventsource.c:79
        filter = 0x555555639660
        node = <optimized out>
        tmp_list = 0x5555556653a0 = {0x555555639660}
        result = <optimized out>
#21 0x00007ffff744af7a in gdk_event_source_translate_event (xevent=0x7fffffffd780, event_source=0x5555555a3b80) at gdkeventsource.c:198
        filter_window = <optimized out>
        dpy = 0x555555577090
        event = 0x5555555a29e0
        result = GDK_FILTER_CONTINUE
        event_translator = 0x0
        event = <optimized out>
        xevent = {type = 35, xany = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443}, xkey = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, state = 0, keycode = 2, same_screen = 1}, xbutton = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, state = 0, button = 2, same_screen = 1}, xmotion = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, state = 0, is_hint = 2 '\002', same_screen = 1}, xcrossing = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, mode = 0, detail = 2, same_screen = 1, focus = 0, state = 16}, xfocus = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, mode = 46832, detail = 0}, xexpose = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, x = 46832, y = 0, width = 1434651296, height = 21845, count = 0}, xgraphicsexpose = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, drawable = 4294967443, x = 46832, y = 0, width = 1434651296, height = 21845, count = 0, major_code = 294, minor_code = 0}, xnoexpose = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, drawable = 4294967443, major_code = 46832, minor_code = 0}, xvisibility = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, state = 46832}, xcreatewindow = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832, x = 1434651296, y = 21845, width = 0, height = 294, border_width = 0, override_redirect = 3280640}, xdestroywindow = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832}, xunmap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, from_configure = 1434651296}, xmap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, override_redirect = 1434651296}, xmaprequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832}, xreparent = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, parent = 93824995232416, x = 0, y = 294, override_redirect = 0}, xconfigure = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, x = 1434651296, y = 21845, width = 0, height = 294, border_width = 0, above = 0, override_redirect = 0}, xgravity = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, x = 1434651296, y = 21845}, xresizerequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, width = 46832, height = 0}, xconfigurerequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832, x = 1434651296, y = 21845, width = 0, height = 294, border_width = 0, above = 0, detail = 0, value_mask = 1}, xcirculate = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, place = 1434651296}, xcirculaterequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832, place = 1434651296}, xproperty = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, atom = 46832, time = 93824995232416, state = 0}, xselectionclear = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, selection = 46832, time = 93824995232416}, xselectionrequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, owner = 4294967443, requestor = 46832, selection = 93824995232416, target = 1262720385024, property = 14090241509949440, time = 0}, xselection = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, requestor = 4294967443, selection = 46832, target = 93824995232416, property = 1262720385024, time = 14090241509949440}, xcolormap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, colormap = 46832, new = 1434651296, state = 21845}, xclient = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, message_type = 46832, format = 1434651296, data = {b = "\000\000\000\000&\001\000\000\000\000\000\000\000\017\062\000\000\000\000", s = {0, 0, 294, 0, 0, 0, 3840, 50, 0, 0}, l = {1262720385024, 14090241509949440, 0, 8589934592, 1}}}, xmapping = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, request = 46832, first_keycode = 0, count = 1434651296}, xerror = {type = 35, display = 0x57ad4d, resourceid = 0, serial = 93824992374928, error_code = 147 '\223', request_code = 0 '\000', minor_code = 0 '\000'}, xkeymap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, key_vector = "\360\266\000\000\000\000\000\000\240\n\203UUU\000\000\000\000\000\000&\001\000\000\000\000\000\000\000\017\062"}, xgeneric = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, extension = 147, evtype = 1}, xcookie = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, extension = 147, evtype = 1, cookie = 46832, data = 0x555555830aa0}, pad = {140733193388067, 5745997, 0, 93824992374928, 4294967443, 46832, 93824995232416, 1262720385024, 14090241509949440, 0, 8589934592, 1, 16, 576, 32, 93824994564688, 0, 608, 32, 93824994564720, 0, 640, 32, 93824994564752}}
        xdisplay = 0x555555577090
        event_source = 0x5555555a3b80
        display_x11 = 0x5555555880e0 [GdkX11Display]
#22 0x00007ffff744af7a in _gdk_x11_display_queue_events (display=0x5555555880e0 [GdkX11Display]) at gdkeventsource.c:341
        event = <optimized out>
        xevent = {type = 35, xany = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443}, xkey = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, state = 0, keycode = 2, same_screen = 1}, xbutton = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, state = 0, button = 2, same_screen = 1}, xmotion = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, state = 0, is_hint = 2 '\002', same_screen = 1}, xcrossing = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, root = 46832, subwindow = 93824995232416, time = 1262720385024, x = 0, y = 3280640, x_root = 0, y_root = 0, mode = 0, detail = 2, same_screen = 1, focus = 0, state = 16}, xfocus = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, mode = 46832, detail = 0}, xexpose = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, x = 46832, y = 0, width = 1434651296, height = 21845, count = 0}, xgraphicsexpose = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, drawable = 4294967443, x = 46832, y = 0, width = 1434651296, height = 21845, count = 0, major_code = 294, minor_code = 0}, xnoexpose = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, drawable = 4294967443, major_code = 46832, minor_code = 0}, xvisibility = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, state = 46832}, xcreatewindow = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832, x = 1434651296, y = 21845, width = 0, height = 294, border_width = 0, override_redirect = 3280640}, xdestroywindow = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832}, xunmap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, from_configure = 1434651296}, xmap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, override_redirect = 1434651296}, xmaprequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832}, xreparent = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, parent = 93824995232416, x = 0, y = 294, override_redirect = 0}, xconfigure = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, x = 1434651296, y = 21845, width = 0, height = 294, border_width = 0, above = 0, override_redirect = 0}, xgravity = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, x = 1434651296, y = 21845}, xresizerequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, width = 46832, height = 0}, xconfigurerequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832, x = 1434651296, y = 21845, width = 0, height = 294, border_width = 0, above = 0, detail = 0, value_mask = 1}, xcirculate = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, event = 4294967443, window = 46832, place = 1434651296}, xcirculaterequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, parent = 4294967443, window = 46832, place = 1434651296}, xproperty = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, atom = 46832, time = 93824995232416, state = 0}, xselectionclear = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, selection = 46832, time = 93824995232416}, xselectionrequest = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, owner = 4294967443, requestor = 46832, selection = 93824995232416, target = 1262720385024, property = 14090241509949440, time = 0}, xselection = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, requestor = 4294967443, selection = 46832, target = 93824995232416, property = 1262720385024, time = 14090241509949440}, xcolormap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, colormap = 46832, new = 1434651296, state = 21845}, xclient = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, message_type = 46832, format = 1434651296, data = {b = "\000\000\000\000&\001\000\000\000\000\000\000\000\017\062\000\000\000\000", s = {0, 0, 294, 0, 0, 0, 3840, 50, 0, 0}, l = {1262720385024, 14090241509949440, 0, 8589934592, 1}}}, xmapping = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, request = 46832, first_keycode = 0, count = 1434651296}, xerror = {type = 35, display = 0x57ad4d, resourceid = 0, serial = 93824992374928, error_code = 147 '\223', request_code = 0 '\000', minor_code = 0 '\000'}, xkeymap = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, window = 4294967443, key_vector = "\360\266\000\000\000\000\000\000\240\n\203UUU\000\000\000\000\000\000&\001\000\000\000\000\000\000\000\017\062"}, xgeneric = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, extension = 147, evtype = 1}, xcookie = {type = 35, serial = 5745997, send_event = 0, display = 0x555555577090, extension = 147, evtype = 1, cookie = 46832, data = 0x555555830aa0}, pad = {140733193388067, 5745997, 0, 93824992374928, 4294967443, 46832, 93824995232416, 1262720385024, 14090241509949440, 0, 8589934592, 1, 16, 576, 32, 93824994564688, 0, 608, 32, 93824994564720, 0, 640, 32, 93824994564752}}
        xdisplay = 0x555555577090
        event_source = 0x5555555a3b80
        display_x11 = 0x5555555880e0 [GdkX11Display]
#23 0x00007ffff7414054 in gdk_display_get_event (display=display@entry=0x5555555880e0 [GdkX11Display]) at gdkdisplay.c:438
        __FUNCTION__ = "gdk_display_get_event"
#24 0x00007ffff744ac26 in gdk_event_source_dispatch (source=source@entry=0x5555555a3b80, callback=<optimized out>, user_data=<optimized out>) at gdkeventsource.c:363
        display = 0x5555555880e0 [GdkX11Display]
        event = <optimized out>
#25 0x00007ffff7e1efd0 in g_main_dispatch (context=0x55555556ca10) at ../glib/gmain.c:3189
        dispatch = <optimized out>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x5555555a3b80
        current = 0x5555555c0910
        i = 0
        __FUNCTION__ = "g_main_dispatch"
#26 0x00007ffff7e1efd0 in g_main_context_dispatch (context=context@entry=0x55555556ca10) at ../glib/gmain.c:3854
#27 0x00007ffff7e1f368 in g_main_context_iterate (context=0x55555556ca10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3927
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 5
        fds = 0x55555568ff50
#28 0x00007ffff7e1f6b3 in g_main_loop_run (loop=0x55555556cea0) at ../glib/gmain.c:4123
        __FUNCTION__ = "g_main_loop_run"
#29 0x000055555555729c in main (argc=<optimized out>, argv=<optimized out>) at core/main.c:579
        act = {__sigaction_handler = {sa_handler = 0x5555555577a0 <sigterm_handler>, sa_sigaction = 0x5555555577a0 <sigterm_handler>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        empty_mask = {__val = {0 <repeats 16 times>}}
        meta_args = {save_file = 0x0, display_name = 0x0, client_id = 0x0, replace_wm = 1, disable_sm = 0, print_version = <optimized out>, sync = <optimized out>, composite = <optimized out>, no_composite = <optimized out>, no_force_fullscreen = <optimized out>}
        log_domains = {0x0, 0x555555558016 "marco", 0x55555555801c "Gtk", 0x555555558020 "Gdk", 0x555555558024 "GLib", 0x555555558029 "Pango", 0x55555555802f "GLib-GObject", 0x55555555803c "GThread"}
        i = <optimized out>
        channel = <optimized out>
(gdb) 
```
Full stacktrace with all Threads
https://www.dropbox.com/s/lyfcwwmus8uuhil/marco-stacktrace?dl=0

It happens several time here. Looks like marco is quite unstable with this feature.

**Comment by raveit65** [comment]
Ok, now X was freezed :/

**Comment by vkareh** [comment]
Alright, this is definitely unstable.

I've started another branch and I'm going to do smaller batches of cherry-picking. Let's do this slowly.

**Comment by lukefromdc** [comment]
This sort of complex thing can definely take a while. The port of Caja from libunique to GtkApplication was based on the same change in Nautilus but still took months of work to really get right. Keep plugging and you will get there.

**Pull request closed without merging**
