### PR TITLE
frames: avoid deprecated 'gtk_widget_set_double_buffered'

### PR DESCRIPTION
**Pull request by sc0w**
please, don't push to the 1.22 release

EDIT: latest changes:

based in the mutter commits:

https://gitlab.gnome.org/GNOME/mutter/commit/b8b0dc5c78008647f5833f63d88456025f17bd08

https://gitlab.gnome.org/GNOME/mutter/commit/669c9da2a48d9a5573edee09065b8558c1d07035

### CODE REVIEW

**Comment by sc0w** [comment]
@lukefromdc yes, confirmed.

With latest changes: I have tested and all seems to work fine, the build is ok without no new warnings in the affected code, and clang static analyzer doesn't show me new warnings.

@lukefromdc please test again.

**Comment by raveit65** [comment]
Is this really save to remove?
I found only this discussions which doesn't make it more clearer.
https://mail.gnome.org/archives/gtk-devel-list/2014-November/msg00039.html
If i understand it correctly, than it seems only save to remove for wayland, but not for x11.
But maybe you found better docs than me?

**Comment by raveit65** [comment]
Here is a good explanation for this function.
https://people.gnome.org/~shaunm/girdoc/C/Gtk.Widget.set_double_buffered.html

**Comment by sc0w** [comment]
@raveit65 

It is needed remove it, in gtk4 the function is gone:

https://gitlab.gnome.org/GNOME/gtk/commit/4a95f8802c22971976dc50e8818af6256218a54d

The commits from mutter here have 4 years old without changes, so, I suppose this code is safe.

**Pull request merged**
