### PR TITLE
Implemented tabpopup when moving window to different workspace

### PR DESCRIPTION
**Pull request by ozeidan**
Hi again guys,
I implemented moving a window to a neighbouring workspace 'properly', it's now similar to how the workspace switching is implemented. This allowed me to make the tabpopup also show up when moving as you can see in this gif:

tabpopup

This solves issue #314. 

I believe it works fairly well, the only unfinished thing being how I handled getting the correct MetaKeyBindingAction in file keybindings.c at line 2742, which is a small hack. For the window move keybindings (up, down, left, and right) this call returned values from the range 94-97 which is why I hardcoded the new enum variants in prefs.h at line 199 like this:
```

...
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_LEFT = 94,
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_RIGHT = 95,
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_UP = 96,
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_DOWN = 97
 } MetaKeyBindingAction;

```
But I am pretty sure this only works on my machine. A little help on this would be appreciated.

### CODE REVIEW

**Comment by raveit65** [comment]
This PR (with the hack) works well here on my system and i like that the moved window looks different than other windows in tabpopup.
With 36 workspaces and several horizontal lines the tabpopup looks a bit like oldschool tetris now, when moving a window :-)
Sorry, i can't help with the hack, i am more a specialist in gtk3 themes and rpm package maintainer in fedora.
But i will call the other guys.
@monsta @lukefromdc @XRevan86 @vkareh @sc0w 
Can you please help?

**Comment by TomaszGasior** [comment]
Works great!!! I really like it and I hope it will be part of next MATE release. Thanks, ozeidan.

**Comment by sc0w** [comment]
@ozeidan 

In `keybindings.c`, on the function:
```

handle_workspace_switch_or_move  (MetaDisplay    *display,
                                  MetaScreen     *screen,
                                  MetaWindow     *window,
                                  XEvent         *event,
                                  MetaKeyBinding *binding,
                                  guint           is_move)
```

why **guint** ?

I see you handle that value with `TRUE` and `FALSE`, why not **gboolean** ? (and the indentation is wrong there)

@lukefromdc 

you can move the active window to another workspaces with:
`[control] + [shift] + [alt] + [arrows]`

**Comment by lukefromdc** [comment]
Turns out that works in compiz-reloaded too, giving a rather flashy effect if combined with the rotating cube. Thus this PR should be good for behavioral consistancy between Marco and Compiz, the two WM's most likely to be used in MATE.

**Comment by ozeidan** [comment]
@sc0w you are right, I changed that.

**Comment by lukefromdc** [comment]
Merged with 
https://github.com/mate-desktop/marco/commit/9e2b7eff713b6881a60538e08e222dad0d364647

**Comment by raveit65** [comment]
@ozeidan @lukefromdc @sc0w @monsta 
...
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_LEFT = 94,
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_RIGHT = 95,
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_UP = 96,
+  META_KEYBINDING_ACTION_WORKSPACE_MOVE_DOWN = 97
 } MetaKeyBindingAction;

```
Guys, can this hardcoding be a problem with non-western or a exotic keyboard layout?

**Comment by lukefromdc** [comment]
I have no easy way to test that, as I could easily disable getting back to a layout I can actually use. We can revert this if an issue is likely, or simply remove the hardcoded keybindings with another commit unless all the default keybindings are hardcoded. Are these keybindings users can reset like most of them?

**Comment by lukefromdc** [comment]
I just realized the flags from libmatekbd can be used to recover using only the mouse and was able to play with this. I looked a a whole bunch of keyboard arrangements, could not find one where these particular keys got any change beyond some name variations. I then added Persian Kurdish and Afghani layouts and found that moving a window with these in Marco in either of these worked exactly the same. This does not mean no keyboard arrangement where these are different exists, but I was not able to find one that broke this in a short test.

**Pull request closed without merging**
