### PR TITLE
delete: remove old code

### PR DESCRIPTION
**Pull request by rbuj**
See https://gitlab.gnome.org/GNOME/metacity/commit/da6ff49008e3a20a4bac05e10a0ac62035f472ae

### CODE REVIEW

**Comment by muktupavels** [comment]
Include original author and date.

**Comment by rbuj** [comment]
@muktupavels 
done

**Comment by muktupavels** [comment]
That is not what I meant... Why you just don't use original commit?

**Comment by rbuj** [comment]
Imported in PR #466

**Pull request closed without merging**
