### PR TITLE
Backport/1 reset visible borders

### PR DESCRIPTION
**Pull request by vkareh**
1. #503

### CODE REVIEW

**Comment by raveit65** [comment]
@yetist 
All this PRs failed to build because of generating ccpcheck results in fedora build.
I think it is this line which causes the issue.
https://github.com/mate-desktop/mate-dev-scripts/blob/master/travis/gen-index.sh#L136
But why?
Travis building of first huge PR was fine https://github.com/mate-desktop/marco/pull/503
See https://travis-ci.org/mate-desktop/marco/builds

**Comment by sc0w** [comment]
> @yetist
> All this PRs failed to build because of generating ccpcheck results in fedora build.
> I think it is this line which causes the issue.

I think it happens probably because the same commit is in two PRs, I think travis will be ok in master when merged.

**Comment by raveit65** [comment]
> I think it happens probably because the same commit is in two PRs, I think travis will be ok in master when merged.

This shouldn't happen. It's normal business to split PRs in smaller ones.
If ccpcheck implementation can't handle this that this should be removed from fedora builds at travis-CI.

**Comment by sc0w** [comment]
I noticed if the job is restarted here, in PR https://github.com/mate-desktop/marco/pull/503 the job of the same commit is restarted too, I think this is a travis issue

@yetist thoughts ?

**Pull request closed without merging**
