### PR TITLE
Add tile keybinds (Fix #104, #127)

### LINKED ISSUE #104: Add keybindings for tiling windows
After enabling the window tiling feature through the "Windows" dialog in the control center, no entries regarding this feature appear in the "Keyboard Shortcuts" dialog.

Please add the possibility to bind tiling a window to a keyboard shortcut.

Possible labels: "Tile window to the left/right".

Arch Linux
marco 1.8.0-1
mate-control-center 1.8.1-1
mate-desktop 1.8.0-3

### PR DESCRIPTION
**Pull request by micove**
Hello:

The requested feature in Issue #104 and #127 was for a key-bind to tile the windows not just move them to the side. The commit messages are fairly documented but to summarize.

The 1st commit adds the schema data.

The 2nd commit refracts code from the unused function "handle_toggle_tiled" and puts it to use in handle_tile_to_side_backend. The refracted code is untouched.

The 3rd commit fixes 3 bugs which makes the new key-bind play nice with existing key-binds. These bugs for the most part are old existing bugs which I found while testing that the pull request works.

I tested this with on a completely up to date Debian/sid system.

Note: I forgot  that using '#' in the commit messages make github reference that pull request number. Sorry about that.

Hope this helps.

### CODE REVIEW

**Comment by micove** [comment]
Update:

I redid the pull request to undo the refracting and just use handle_toggle_tiled as that is much cleaner than to use 3 new functions. I had to squash the commits to do this so delete the old local repository before doing a local pull request.

It's still basically the same but simplified and fixed some 1-2 extra  issues.

**Comment by infirit** [comment]
Thx, I'll try it out.

**Comment by Hypfer** [comment]
Is it possible to expand this so that left and right side could be split in half?

**Comment by flexiondotorg** [comment]
@stefano-k Please review this for inclusion in MATE 1.10

**Comment by NiceandGently** [comment]
@stefano-k 
This works great and makes tiling support usable for me.
Also with 1.8 it's possible to use it after backporting the 'rework tiling commit' from master branch.
Please review.

**Comment by flexiondotorg** [comment]
Thanks for your contribution.

**Comment by Hypfer** [comment]
Finally. Thanks.

**Pull request merged**
