### PR TITLE
Revert animation changes

### PR DESCRIPTION
**Pull request by monsta**
This reverts https://github.com/mate-desktop/marco/pull/115.
Unfortunately, this leaves marco without **un**minimize animation, but fixes some annoying bugs.

Fixes https://github.com/mate-desktop/mate-applets/issues/128
Fixes https://github.com/mate-desktop/marco/issues/180

@clefebvre @flexiondotorg @raveit65 
please test for any possible regressions :smile:
(with and without compositing)

### CODE REVIEW

**Comment by flexiondotorg** [comment]
I'm in favour, I've been testing a branch with these reverts for a couple of months and it fixes several frequently occurring segfaults.

**Comment by raveit65** [comment]
This fixes stick-notes crash with gtk3.
But i see no minimize animation if using show-desktop applet.
Or did i misread https://github.com/mate-desktop/marco/issues/180  ?
Well, the un-minimize/minimize animations are very poor compare to what is possible with compiz-0.8.9, so i think i can live without it.
Better we have a working sticky-note applet with gtk3.
+1 for reverting

PS, for some reasons i don't find the animation gsettings key anymore, is this removed with another commit?

**Comment by raveit65** [comment]
If i take a look at https://github.com/mate-desktop/marco/pull/115
Will this all reverted?

**Comment by raveit65** [comment]
This revert fixes another serious blocker bug with gtk3 too.
Now wnck applets doesn't crash anymore if panel use transparency and you switch compositor on/off.
So, i increase my vote
++++++++1

**Comment by Samsagax** [comment]
Oh! No problem. That PR was made a while back and was very messy. Feel free to revert it. Will try to rewrite it.

**Comment by monsta** [comment]
> But i see no minimize animation if using show-desktop applet.
Or did i misread #180 ?

The buggy animation described there is gone, that's for sure.

> PS, for some reasons i don't find the animation gsettings key anymore, is this removed with another commit?
It's still there :smile:
```
gsettings get org.mate.interface enable-animations
```
> If i take a look at #115
Will this all reverted?
Some commits are marked as bugfixes.

It seemed to me these were fixes only for other commits there...

**Comment by clefebvre** [comment]
+1 for me.

**Pull request merged**
