### PR TITLE
Test Xres extension before using it.

### PR DESCRIPTION
**Pull request by joakim-tjernlund**

### CODE REVIEW

**Comment by raveit65** [comment]
My crystal ball is broken, for what is your PR good for ?
:)

**Comment by joakim-tjernlund** [comment]
> My crystal ball is broken, for what is your PR good for ? :)

:)  It is related to https://github.com/mate-desktop/marco/issues/746
Marco should not rely on others(libwnck) to have done this for you.

**Review by lukefromdc — APPROVED** [review]
This builds and runs fine with marco in both compositing and noncomposing mode. Note that runtime test was short as I normally run compiz. Didn't get any issues with windows overlapping panels or anything like that.

NOT tested with X2go however as I simply don't have that sort of setup

**Comment by muktupavels** [comment]
> Marco should not rely on others(libwnck) to have done this for you.

Marco does not use libwnck...

**Comment by joakim-tjernlund** [comment]
Turns out that X2Go does not tolerate and call to XResQueryClientIds().
Therefore impl. the test similar to libwnck using a global flag

**Comment by raveit65** [comment]
Problems with x2go seems to be fixed, but it doesn't fix the origin issue  https://github.com/mate-desktop/marco/issues/301, which was fixed by https://github.com/mate-desktop/marco/pull/741

**Comment by joakim-tjernlund** [comment]
> Problems with x2go seems to be fixed, but it doesn't fix the origin issue #301, which was fixed by #741
> 
> Edit: Tested with signal messenger from flathub.

Would be great if applied to 1.26.x too(and a release).
My testing was on 1.26

**Comment by lukefromdc** [comment]
What is the status of this? It is ready to go?

**Comment by raveit65** [comment]
> .............but it doesn't fix the origin issue #301, which was fixed by #741
> 
> Edit: Tested with signal messenger from flathub.

For me this is open.

**Comment by lukefromdc** [comment]
So this needs more work before merge?

**Comment by raveit65** [comment]
No idea, i only wanted to say that origin issue isn't fixed by this PR.

**Comment by joakim-tjernlund** [comment]
I didn't claim it solved any flatpak issues, just X2GO.
There is nothing more to be done here, if you have flatpak issues that is a different problem I think.

**Comment by lukefromdc** [comment]
Thinking everyone who's going to review this already has, we have two different testers (one the writer) finding this fixes the X2go issue, and this is not about any flatpak bugs. Been almost a month and no problems caused by this have cropped up. The new variables are` int`s and a `gboolean` on the stack, so automatically managed and won't leak.

Will merge

**Comment by joakim-tjernlund** [comment]
Thank you, adding it to 1.26 too?

**Comment by lukefromdc** [comment]
I normally only work on the master branch, it's three cherrypicks to make this work but since 4 commits back also related to this will try it

**Comment by lukefromdc** [comment]
Someone else will have to handle releasing a 1.26 point release containing this: just pushed it to the branch but I have never managed the releases

**Comment by lukefromdc** [comment]
Merged to 1.26, distros won't see it until someone release 1.26.2

**Comment by mbkma** [comment]
I will do point releases soon.

**Pull request merged**
