### PR TITLE
Pull request for  #525 -- port changes from master to branch 1.22

### PR DESCRIPTION
**Pull request by insaner**
I hope I did this right. Let me know if I didn't, I'm still new at this whole git/github thing.

### CODE REVIEW

**Comment by raveit65** [comment]
This is a new feature which belongs in in next major release.
Only bug fixes goes into supported stable releases.

**Comment by insaner** [comment]
Would it be possible to create a different branch for it then? I think the features that were implemented are so good (and impact productivity so positively) that it would be a shame for others without the chance of having glib-2.0 >= 2.58.0 (which is only used for one or two lines in master) to miss out on these. I for one have been wanting the ability to change the number of rows in the alt-tab window for perhaps years, and had hard-coded it to be 15 (instead of 5) in my local copy. Let me know if that is possible or reasonable. Thanks again!

**Comment by raveit65** [comment]
You can create a new branch at https://github.com/insaner/marco , or not?
I don't understand why you need an extra branch here.

**Comment by insaner** [comment]
Sorry, I'm still quite new to git/github, so I thought it was something that made sense, ie, so that people trying to do the same thing as me could easily find the branch from official sources. I will of course leave mine up for whoever could potentially benefit from it.

Quick question, in the future, if I did end up coding some new feature, since I can't compile master, and hence can't develop code for master, how would I go about doing the pull request in such a case? Would I be dead in the water until I /do/ have glib-2.0 >= 2.58.0?

**Comment by raveit65** [comment]
Which distro use glib-2.0 <= 2.58.0 ?
Sounds very old. Does this distro receive MATE 1.22 updates?
Fedora 30:
```
[rave@mother ~]$ rpm -qa glib2
glib2-2.60.4-1.fc30.x86_64
```

**Comment by raveit65** [comment]
Btw. If you don't delete your repo everybody can read this (closed) PR and can use your code.
```
git checkout -b insaner-master 1.22
git pull https://github.com/insaner/marco.git master
```

**Comment by insaner** [comment]
Sorry for the delay, I've been distracted by resolving many other issues after the upgrade. To answer your question:

> Which distro use glib-2.0 <= 2.58.0 ?

This is Fedora 27, I just upgraded a month ago, and Fedora 28 is only available as 64bit, which I have not been able to make the full switch to yet.. working on it. But, in any case, that means that anyone unable to switch to 64bit Fedora will also be stuck at 27 as their maximum, and without  glib-2.0 >= 2.58.0.

I feel this feature is definitely worth it, and has been a feature I've been wanting for years now. (I patched my marco back in Feb 2018 to hard code it to 15 columns instead of 5. (I discussed this on IRC - with user vkareh back then, and even mulled the idea of writing the code to make it configurable with dconf, which @osch 's #497 also did -- awesome!)

I guess I should ask again: in the future, if I did end up coding some new feature, since I can't compile master, and hence can't develop code for master, how would I go about doing the pull request in such a case? Would I be dead in the water until I /do/ have glib-2.0 >= 2.58.0?

**Comment by raveit65** [comment]
> This is Fedora 27, I just upgraded a month ago, and Fedora 28 is only available as 64bit, which I have not been able to make the full switch to yet.. working on it. But, in any case, that means that anyone unable to switch to 64bit Fedora will also be stuck at 27 as their maximum, and without glib-2.0 >= 2.58.0.

Hmm, 32bit repos are there for 28/29/30, for example `glib2-2.60.5-1.fc30.i686.rpm`
https://koji.fedoraproject.org/koji/buildinfo?buildID=1310515
It is possible to update a f27 to f30 for i686 with `dnf` from command line.
You only need install fedora-repos package for f30 by hand.
I did that since f9 in this way , no other tools are needed.

Or download i386 live images for f28/29/30 via torrent.
https://torrent.fedoraproject.org/

For  f31 there is a discussion at fedora-devel to stop providing i686 repos.

Last but not least, why using very old hardware which do not support x86_64?
Have you ever tried to install x86_64?
My last hardware which did not support x86_64 was from last century ;)

**Comment by insaner** [comment]
Oh interesting, I had no idea koji was providing 32bit releases. I had disabled the koji repo some time ago. Good to know, thanks. It doesn't help that rpm.pbone.net does not host koji files though, which is where I go to get individual rpms when everything breaks.. or when they are not available from yum/dnf for some reason.

My hardware is actually not old, and fully 64bit capable (I usually run a 64bit kernel), the switch to 64bit has been complicated by other factors, but hopefully in the next few months it won't be an issue. I do want to still have the option to boot into either 32bit or 64bit (as in, full os, not just the kernel), which I had almost accomplished by repackaging some rpms for my previous release as "compat"-type packages.. since fedora doesn't do multilib like other distros. But it soon became clear that it would not be a trivial task (I think I got stuck at Xorg).

Out of curiosity, have you ever done a cross-grade? Where you just install 64bit rpms and bring your system to 64bit from 32bit? There are stories of success from years ago, but the processes described tend to "skip" describing certain necessary steps, and I have never been able to do it myself.

Not to mention the fact that my dnf and rpm are now broken (since the upgrade), they don't seem to be overwriting files as they're supposed to (like updating an rpm does not overwrite the .so files it's supposed to). Which is very frustrating. No clue what is causing that.

**Comment by raveit65** [comment]
> Oh interesting, I had no idea koji was providing 32bit releases.

No, f28/29/30 is available with normal repos for i686. You don't need koji repo.
Again, i686 repos will be (are) dropped with f31, not with f28!

Btw. Last mate-compiz live iso for f31(rawhide)
https://koji.fedoraproject.org/koji/taskinfo?taskID=36208502

And i am just building Mate-1.23.x for  i386 for rawhide/f30/f29 at fedora copr repo.
https://copr.fedorainfracloud.org/coprs/raveit65/MATE-1.23.x/
You only need to update to f30 or f29 to get 1.23.x rpms.

**Comment by raveit65** [comment]
You might have another problem.
Dnf package-manager gives me a long list of available i686 packages in f30.
```
[root@mother rave]# LANG=C
[root@mother rave]# dnf list *.i686
Last metadata expiration check: 0:00:51 ago on Sat Jul 20 11:38:45 2019.
Installed Packages
bzip2-libs.i686                      1.0.6-29.fc30                       @fedora
glibc.i686                           2.29-15.fc30                        @updates
libgcc.i686                          9.1.1-1.fc30                        @updates
ncurses-libs.i686                    6.1-10.20180923.fc30                @fedora
zlib.i686                            1.2.11-15.fc30                      @fedora
Available Packages
4th.i686                             3.62.5-3.fc30                       fedora 
4th-devel.i686                       3.62.5-3.fc30                       fedora 
4ti2-devel.i686                      1.6.9-2.fc30                        fedora 
4ti2-libs.i686                       1.6.9-2.fc30                        fedora 
AllegroOGG.i686                      1.0.3-22.fc30                       fedora 
AllegroOGG-devel.i686                1.0.3-22.fc30                       fedora 
AntTweakBar.i686                     1.16-8.fc28                         fedora 
AntTweakBar-devel.i686               1.16-8.fc28                         fedora 
Box2D.i686                           2.3.1-10.fc30                       fedora 
Box2D-devel.i686                     2.3.1-10.fc30                       fedora 

<cut>
```
full list at: https://www.dropbox.com/s/6snnuol1mh1ej6x/i686-packages-f30?dl=0
Damned, i need to drop installed i686 packages ;)

**Comment by raveit65** [comment]
Btw, discussion at fedora-devel list about dropping i686 repositories.
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/T5ZV5WCJ7U7BFQXC6RTNG3AIHXOORYOC/

Btw. I like this change ;)

**Comment by insaner** [comment]
Oh I see what happened now. They moved the 32bit files to a single 64bit directory:
https://archive.fedoraproject.org/pub/fedora/linux/releases/28/Everything/x86_64/os/Packages/g/

Instead of also having an i686 directory. Weird. It explains much now. I wonder if in so doing they also finally fixed the multilib issue. I guess I now have to look into upgrading (again) soon.

**Pull request closed without merging**
