### PR TITLE
build: add --enable-more-warnings configure flag

### PR DESCRIPTION
**Pull request by rbuj**
- Remove -ansi from CFLAGS.
 - By default, CFLAGS:
      -Wall -Wchar-subscripts -Wmissing-declarations
      -Wnested-externs -Wpointer-arith -Wcast-align
      -Wsign-compare
 - If --enable-more-warnings, add -Wextra to CFLAGS.
 - Requires autoconf-archive package.

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
We can also update meson build https://github.com/mate-desktop/marco/blob/master/meson.build#L46
And you can add all this new CFLAGS to travis config.
https://github.com/mate-desktop/marco/blob/master/.travis.yml#L173

@yetist 
Is it possible to add --enable-more-warnings to meson build?

**Comment by raveit65** [comment]
@rbuj 
Can we add `-Werror=format-security` to default CFLAGS please?

**Comment by raveit65** [comment]
Just rebased to get the build fix from master.

**Comment by rbuj** [comment]
meson.build: `-Werror=format-security` and `-Werror=format=2` flags must be checked together.
```shell
$ meson setup --wipe builddir
...
Compiler for C supports arguments -Wcast-align: YES
Compiler for C supports arguments -Wchar-subscripts: YES
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES
Compiler for C supports arguments -Wmissing-declarations: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wnested-externs: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Wshadow: YES
Compiler for C supports arguments -Wsign-compare: YES
Compiler for C supports arguments -Wall: YES
...
```

**Comment by yetist** [comment]
> We can also update meson build https://github.com/mate-desktop/marco/blob/master/meson.build#L46

I think we can remove the comment of that lines, to get more build warnings.

**Comment by raveit65** [comment]
@rbuj 
I agree with @yetist to uncomment the CFLAG_WARNINGS in meson.build to finishing this PR.
Or not?

**Comment by yetist** [comment]
Maybe I should do the code indent first, and then make the real changes?

**Pull request merged**
