### PR TITLE
Fullscreen dual screen fix

### PR DESCRIPTION
**Pull request by rcaridade145**
This PR backports the commit https://gitlab.gnome.org/GNOME/metacity/commit/1fafd279006ece8cf664fd777143cdfafbefad6d on Metacity to Marco.
It should fix issue #316 .
I don't have multi monitors so i cannot test.

### CODE REVIEW

**Comment by raveit65** [comment]
Why a merge commit?
You only need to start with fresh copy from our master.

**Comment by raveit65** [comment]
I don't like the name of the commit ` Backport of metacity commit https://gitlab.gnome.org/GNOME/metacity/commit/1fafd279006ece8cf664fd777143cdfafbefad6d`
This is a description what you did but not a description what the commit does.
Reading this in git history is meaningless.
Why not using commit header of origin commit?

**Comment by rcaridade145** [comment]
Hope it is better now.

**Comment by raveit65** [comment]
Better but the link doesn`t belong in commit header.
Move it to commit body please.
Do you see links in commit headers of Mate or gnome git normaly?

**Comment by raveit65** [comment]
Commit header = a short description what commit does
-------------------------------------------------------------------------
A Blank line to separate commit header from body
-------------------------------------------------------------------------
Commit body = more detail description and links. etc

**Comment by raveit65** [comment]
Hmm, now marco crashes every time when i am opening a link from an application to another application. Eg. opining a weblink in thunderbird to firefox, or a image in from caja int eom, etc.

**Comment by rcaridade145** [comment]
The issue should be now fixed.

**Comment by raveit65** [comment]
https://patch-diff.githubusercontent.com/raw/mate-desktop/marco/pull/580.patch
8 Patches ???
Branch has conflicts!

**Comment by rcaridade145** [comment]
Sorry i messed up the commits :S . I am going to close this pull request and create a new one from scratch.

**Pull request closed without merging**
