### PR TITLE
Use the native window menu for windows with Gtk3 CSDs

### PR DESCRIPTION
**Pull request by vfscanf**
Gtk3 applications that utilize the GtkHeaderBar widget (basically windows with CSD) only show a very minimal "fallback" window menu when right clicking on the title bar. Gtk3 introduced an API that allows the window manager to display the native window menu, even on CSD windows.

To do that we have to register a X11 Atom. Then, when somebody right clicks on the CSD title bar, we get a client event, which we can handle appropriately.

xfwm4 already implements this, here is the relevant patch: https://mail.xfce.org/pipermail/xfce4-commits/2015-February/059211.html . There is also a bug report for this feature #334 .

This PR adds support for that API. I have tested it on my system, and it works fine so far.

### CODE REVIEW

**Comment by TomaszGasior** [comment]
Works great for me with marco from master.  Thanks, vfscanf!

**Comment by vfscanf** [comment]
There is one small issue that I found myself. When the title bar from a window is offscreen, the window menu shows an additional option "Move Titlebar On screen". The check that decides whether to show that option doesn't work for CSD windows, as they have no titlebar from the viewpoint of the window manager.

This check will always decide that the window is offscreen for CSD windows. As a result, this option is always shown for CSD windows, but it doesn't do anything. I will push another commit that fixes this faulty check so it doesn't show this option for CSD windows.

**Comment by TomaszGasior** [comment]
@vfscanf, are you able to also fix this bug If user presses Alt+Space to open window context menu:
marco: 
alt-space-marco
xfwm4 (good position of context menu):
alt-space-xfwm4

**Comment by raveit65** [comment]
@TomaszGasior 
Can you please open a report for it instead of hijacking this PR?
Thank you.

**Comment by TomaszGasior** [comment]
it seems to me it's related to this PR.

**Comment by raveit65** [comment]
Second commit removes the wrong entry.

**Comment by raveit65** [comment]
> It seems to me it's related to this PR. When we are adding native menu to CSD-windows we can also fix its position at the same time.

Nope, the issue with wrong position of the menu when pressing alt+space on csd-windows still exists without using this PR.
So, please file out a new report for it, it is confirmed.

**Comment by raveit65** [comment]
Thanks

**Pull request merged**
