### PR TITLE
make icon size configurable

### PR DESCRIPTION
**Pull request by osch**
see #479

### CODE REVIEW

**Comment by raveit65** [comment]
This works very nice and icons are scaling fine with a HIDPI monitor and a very huge icon size. Screenshot is with 420px icon-size :)
Bildschirmfoto zu 2019-04-14 14-30-06
Changing icon-size is also possible with using thumbnail-previews, which is great.
But i think in case of using thumbnails we need a size limit, because icons don't display if previews are smaller than the chosen icon size.
Than we get and errors in .xsession-errors log like this, in my case when icon-size is > 220px for windows with default size.
```
(marco:17563): GdkPixbuf-CRITICAL **: 14:12:12.860: gdk_pixbuf_composite: assertion 'dest_y >= 0 && dest_y + dest_height <= dest->height' failed
```
Beside from that this is a very nice feature.

**Comment by sc0w** [comment]
yes, I think it needs limits to big and small icons, it prevents unexpectedly behavior if user put a lot of bigger/smaller icon by mistake

and I think @alexarnaud will like this new feature for accessibility reasons :)

**Comment by osch** [comment]
The error `gdk_pixbuf_composite: assertion` is not new: you can also have this error with current marco if you resize the window such that e.g. the height is much smaller than the width: see the following screenshot from alt+tab popup: both window thumbnails on the left are firefox windows but the first one does not contain an icon because the icon does not fit into the provided height and therefore causes the assertion.

image

**Comment by raveit65** [comment]
Cool,
last commit does what it promised and scales down the icon, if the thumbnail is smaller than icon-size.
But 1024px seems to be very large. With 1024px the icon doesn't fit in my UHD-monitor (3840x2160px).
Bildschirmfoto zu 2019-04-14 22-12-14
For which videowall setup you need such a big icon?
I think a limit of 480px should be sufficient. 640x480 is smallest monitor size.

**Comment by sc0w** [comment]
I think the max can be calculated depending of the screen monitor dimensions

**Comment by osch** [comment]
I personally only need icon size 32 so I'm also fine with max size 480. The motivation for choosing 1024 as max value was not "which max value would be enough", it was instead the question "which max value is beyond resonable max value and does not harm the principle functionality of the appliation". And if you say 480 is reasonable max value, than I'm glad that 1024 is not below. IMHO it's always best to let the user decide. Who knows how big screens will be in the future? But as I said: I'm also fine with max value 480. 

I also think it could be possible to calculate max value from screen dimensions, but at least a fixed max value must be provided in the gschema.xml . But where's the problem? If the user chooses a max value that does not make sense, the user will recognise this and change the value back.

**Comment by rbuj** [comment]
META_MIN_ICON_SIZE should be 8.
Common png icon sizes: 8, 16, 22 , 24, 32, 48. (svg: multiple of 16=16..64)
png logo size is multiple of 128 (usually 256). (svg: multiple of 128=128...512)

**Comment by rbuj** [comment]
In caja:
64 is the default preview size (it can be set with dconf).
Icon scale: 48* is the base (1:1). 16* is 33%, 24* is 50%, 32* is 66%, 72 is 150%, 96 is 200%, 192 is 400%.

**Comment by osch** [comment]
Min icon size 6 works perfectly here on my low dpi screen. I don't see any problems with min icon size 6. What's wrong if a user decides to use icon size 6 and it does work? 

I cannot reproduce problems with icon size 128 or larger here. See the following screenshot with icon size 128:

image

Perhaps I'm missing something and this is not the "window switcher preview"?

**Comment by rbuj** [comment]
@sc0w 
It's a great improvement. It requires fixing some icons in the **High Contrast Inverse** theme, since some icons appears blurred. Fix the frame color of the window selector. Create the symbolic link: mate-desktop -> mate.

Captura de pantalla a 2019-04-15 11-48-35


off-topic:
**High Contrast Inverse** theme it's not detected as [high contrast theme in firefox](https://support.mozilla.org/en-US/kb/accessibility-features-firefox-make-firefox-and-we#w_using-a-high-contrast-theme)

**Comment by lukefromdc** [comment]
One possiblity is that my icon theme(a custom one) by not providing some of the larger icons may have been an issue. Since I normally run compiz and my own GTK and icon themes, I might not notice some things in marco and some icon theme or GTK theme dependent things do act differently.

**Comment by raveit65** [comment]
@rbuj 
min size =6px is OK if using 
```
[rave@mother Schreibtisch]$ gsettings get org.mate.Marco.general compositing-fast-alt-tab
true
```
, which was the first intention of pull request.
Bildschirmfoto zu 2019-04-17 14-06-07
Well, the icon is small but you can see which icon is it.

It seems there is a different with the icon-size if using thumbnails.
I can confirm that 6 or 8px is nearly a point, or an icon without any meaning.
For me everything < 16px doesn't make any sense when using thumbnails.

**Comment by raveit65** [comment]
@rbuj 
Is the min/max icon-size really a show stopper for you?
Or can we merge it like it is?
6px is working for me if using non thumbnails.

**Comment by rbuj** [comment]
The desktop [UI standard is still 96 dpi](https://www.eizo.se/knowledge/monitor-expertise/understanding-pixel-density/).
```
pixels = 6;
dpi = 96;
mm = 25.4 * pixels / dpi;
mm = 1.5875
```
Recomended [viewing distance](http://ergo.human.cornell.edu/ergoguide.html): 1 arm (0.8m)

I can't distinguish an image of 1.6x1.6mm at 0.8m.

**Comment by raveit65** [comment]
And using 8px makes you mathematics results better?
My eyes are not the best but i can recognize the icons if i don't use using thumbnails.
Please don't forget the merge this PR, i have to delete it from my TODO list

**Comment by sc0w** [comment]
I think it is a good idea to do the same in the workspace switcher :)

**Pull request merged**
