### PR TITLE
Remove the copyright information when printing the version from the command line

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
With this, we get 
`marco-2.0`
as the output of the --version command.
With master, we get 
`marco 1.25.0`
followed by all the copyright information. Thus we do NOT print the package version with this, only the ABI version

**Comment by rbuj** [comment]
Can you check the value of PACKAGE_STRING in config.h file after running configure?
```
$ ./autogen.sh --prefix=/usr &> /dev/null && grep PACKAGE_STRING config.h
#define PACKAGE_STRING "marco 1.25.0"
```
Tested on Fedora:
```
$ marco --version
marco 1.25.0
```

**Comment by rbuj** [comment]
Ok, it's a messon build issue:
```
$ meson --prefix=/usr builddir && grep PACKAGE_STRING builddir/config.h
#define PACKAGE_STRING "marco-2.0"
```

**Comment by rbuj** [comment]
@lukefromdc done

**Comment by rbuj** [comment]
Test:
```
$ meson --prefix=/usr builddir
$ cd builddir
$ ninja
$ sudo ninja install
$ marco --version
```

**Review by lukefromdc — APPROVED** [review]
This now works as expected in meson builds, thanks

**Comment by lukefromdc** [comment]
Any updates on this?

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
