### PR TITLE
Migrate from intltool to gettext

### PR DESCRIPTION
**Pull request by yetist**
Known issue:
Some po files will break the building, such as hy.po ko.po mr.po tr.po zu.po

EDIT:
```
rm -f af.gmo && /usr/sbin/msgfmt -c --statistics --verbose -o hy.gmo hy.po
```
If remove `-c` from the command line, it will pass, the Makefile comes from  `/usr/share/gettext/po/Makefile.in.in`
```
105         echo "$${cdcmd}rm -f $${lang}.gmo && $(GMSGFMT) -c --statistics --verbose -o $${lang}.gmo $${lang}.po"; \
106         cd $(srcdir) && rm -f $${lang}.gmo && $(GMSGFMT) -c --statistics --verbose -o t-$${lang}.gmo $${lang}.po && mv t-$${lang}.gmo $${lang}.gmo
```
The other way to fix that is update the msgstr at https://www.transifex.com

### CODE REVIEW

**Comment by yetist** [comment]
Run the follow command on the master branch, it show errors, that should fix first.
```
$ for i in hy.po ko.po mr.po tr.po zu.po;do msgfmt -c $i; echo $?;done
msgfmt: hy.po: warning: PO file header fuzzy
               warning: older versions of msgfmt will give an error on this
hy.po:12: warning: header field 'Project-Id-Version' still has the initial default value
hy.po:1553: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
hy.po:1560: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
msgfmt: found 2 fatal errors
1
msgfmt: ko.po: warning: PO file header fuzzy
               warning: older versions of msgfmt will give an error on this
ko.po:14: warning: header field 'Project-Id-Version' still has the initial default value
ko.po:1202: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
msgfmt: found 1 fatal error
1
msgfmt: mr.po: warning: PO file header fuzzy
               warning: older versions of msgfmt will give an error on this
mr.po:13: warning: header field 'Project-Id-Version' still has the initial default value
mr.po:1222: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
msgfmt: found 1 fatal error
1
msgfmt: tr.po: warning: PO file header fuzzy
               warning: older versions of msgfmt will give an error on this
tr.po:18: warning: header field 'Project-Id-Version' still has the initial default value
tr.po:1296: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
msgfmt: found 1 fatal error
1
msgfmt: zu.po: warning: PO file header fuzzy
               warning: older versions of msgfmt will give an error on this
zu.po:11: warning: header field 'Project-Id-Version' still has the initial default value
0
```

**Comment by raveit65** [comment]
I deleted the translations with format errors at transifex. No idea what was wrong in hy, ko or the other languages.
Hard to fix if you don't understand something. And if fixed wrong project-id warnings.
Any way, i checked all languages with `msgfmt -c` command.
Except the fuzzy header warnings all looks good.

**Comment by raveit65** [comment]
I saw that those format errors were in the suggested translations for a string.
In result it is possible that a translator will pull in the bad formatted translation again.
So, we need to check building by hand before we push a translation update to github after a pull from transifex.
@mate-desktop/core-team ^^^^^^^^^

**Comment by raveit65** [comment]
`/usr/bin/msgfmt: cannot locate ITS rules for 50-marco-desktop-key.xml.in`
https://travis-ci.org/mate-desktop/marco/jobs/531493448#L2072

**Comment by raveit65** [comment]
I don't think this is related to PR.
Now, compiling will create a new marco.pot under /po folder, which is good.
But this line is wrong
`"Content-Type: text/plain; charset=CHARSET\n"`
Should be
`"Content-Type: text/plain; charset=UTF-8\n"`
If this gets in *po files when pulling translations back from transifex building will fail.
Since 1 year we fight against this issue, some repos have this issue and some not.
And always i need to fix *.po files by hand before releasing. 
So my hope dies that switching to getext will fix this issue.

**Comment by raveit65** [comment]
For some reasons we have *.gmo language files in the tarball if using `make distcheck` to create them.
That isn't behavior from master branch.

**Comment by raveit65** [comment]
Ok, normal installation with `sudo make install` doesn't install those *.gmo files, which is good.
But those files doesn't belong in tarball.

**Comment by raveit65** [comment]
Same problem with mate-desktop and mate-backgrounds
https://github.com/mate-desktop/mate-desktop/issues/382
https://github.com/mate-desktop/mate-backgrounds/pull/22#issuecomment-492106967

**Comment by raveit65** [comment]
Last problem is a feature from gettext, not an bug.....

**Pull request merged**
