### PR TITLE
Fix mismatched enums in keybinding detection

### LINKED ISSUE #118: ctrl+alt+tab appears to be broken [$15]
Coffeeking reported this on IRC. I can only tab once and then back. tabbing more than once stops the action completely.

I am on git master and coffeeking was on Marco 1.8.0. I'll see if this also happens in 1.6.
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2843997-ctrl-alt-tab-appears-to-be-broken?utm_campaign=plugin&utm_content=tracker%2F841233&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F841233&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vkareh**
The enum has a mismatched list with regards to the gsettings list of keybindings, which means that switch-panels shows up as switch-windows-all when Tabbing through the popup entries.

Fixes #118

### CODE REVIEW

**Comment by alexarnaud** [comment]
I've tested the fix and I can confirm that it solves the issue #118 Thanks a lot @vkareh :)!

Best regards.

**Comment by alexarnaud** [comment]
@vkareh is it possible for you to backport the fix for 1.20 ?

Best regards.

**Comment by vkareh** [comment]
@alexarnaud - this will need to be discussed with the rest of the team, I'm not a distro maintainer, so I'm not very familiar with the implications of a backport :/

@raveit65, @flexiondotorg - thoughts?

**Comment by raveit65** [comment]
I just tested the PR.
With 2 pannels is it much better, i don't need to use crtl+alt+shift+tab to select both panel.
But with using 3 panels i can only select 2 panels with  crtl+alt+tab.
Here i need to use crtl+alt+shift+tab for selecting the third panel. But this is a bit try&error and doesn't work perfect.

This commit is a bug fix which can be cherry-pick to other branches.
Also to 1.18 if someone plan to release new tarballs here.

**Comment by raveit65** [comment]
Btw. with this PR i can't reproduce https://github.com/mate-desktop/marco/issues/394 any more.

**Comment by vkareh** [comment]
@raveit65 - what do you mean it doesn't work with 3 panels?

**Comment by raveit65** [comment]
Try it out, with more than 2 panels you still select only 2 panels if only using  crtl+alt+tab . Same like before with 2 panels.

**Comment by vkareh** [comment]
hmmm... still works for me, I tried it with 3 and 4 panels. Maybe there's a conflicting setting somewhere? We shoud compare to make sure:
```sh
vkareh@xps-15:~ $ gsettings list-recursively org.mate.Marco.global-keybindings
org.mate.Marco.global-keybindings run-command-terminal '<Control><Alt>t'
org.mate.Marco.global-keybindings switch-to-workspace-left '<Control><Alt>Left'
org.mate.Marco.global-keybindings run-command-window-screenshot '<Alt>Print'
org.mate.Marco.global-keybindings switch-windows-all 'disabled'
org.mate.Marco.global-keybindings run-command-10 'disabled'
org.mate.Marco.global-keybindings run-command-11 'disabled'
org.mate.Marco.global-keybindings run-command-12 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-10 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-1 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-12 'disabled'
org.mate.Marco.global-keybindings panel-run-dialog '<Alt>F2'
org.mate.Marco.global-keybindings switch-to-workspace-11 'disabled'
org.mate.Marco.global-keybindings cycle-windows '<Alt>Escape'
org.mate.Marco.global-keybindings show-desktop '<Control><Alt>d'
org.mate.Marco.global-keybindings switch-to-workspace-4 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-2 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-3 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-7 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-5 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-6 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-8 'disabled'
org.mate.Marco.global-keybindings run-command-screenshot 'Print'
org.mate.Marco.global-keybindings panel-main-menu '<Alt>F1'
org.mate.Marco.global-keybindings cycle-windows-backward 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-prev 'disabled'
org.mate.Marco.global-keybindings cycle-group-backward 'disabled'
org.mate.Marco.global-keybindings cycle-panels-backward 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-right '<Control><Alt>Right'
org.mate.Marco.global-keybindings switch-to-workspace-9 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-down '<Control><Alt>Down'
org.mate.Marco.global-keybindings cycle-group '<Alt>F6'
org.mate.Marco.global-keybindings switch-windows-all-backward 'disabled'
org.mate.Marco.global-keybindings switch-panels-backward '<Control><Alt><Shift>Tab'
org.mate.Marco.global-keybindings switch-windows-backward '<Alt><Shift>Tab'
org.mate.Marco.global-keybindings switch-group '<Alt>grave'
org.mate.Marco.global-keybindings run-command-1 '<Mod4>l'
org.mate.Marco.global-keybindings run-command-3 'disabled'
org.mate.Marco.global-keybindings run-command-4 'disabled'
org.mate.Marco.global-keybindings run-command-5 'disabled'
org.mate.Marco.global-keybindings run-command-6 'disabled'
org.mate.Marco.global-keybindings cycle-panels '<Control><Alt>Escape'
org.mate.Marco.global-keybindings run-command-8 'disabled'
org.mate.Marco.global-keybindings run-command-9 'disabled'
org.mate.Marco.global-keybindings run-command-7 'disabled'
org.mate.Marco.global-keybindings switch-group-backward 'disabled'
org.mate.Marco.global-keybindings rename-workspace 'disabled'
org.mate.Marco.global-keybindings switch-panels '<Control><Alt>Tab'
org.mate.Marco.global-keybindings switch-to-workspace-up '<Control><Alt>Up'
org.mate.Marco.global-keybindings switch-windows '<Alt>Tab'
org.mate.Marco.global-keybindings run-command-2 '<Shift>Print'
vkareh@xps-15:~ $
```
(not sure why gsettings prints in such a random order)

**Comment by raveit65** [comment]
i am using the default valuse here.
```
[rave@mother ~]$ gsettings list-recursively org.mate.Marco.global-keybindings | sort
org.mate.Marco.global-keybindings cycle-group '<Alt>F6'
org.mate.Marco.global-keybindings cycle-group-backward 'disabled'
org.mate.Marco.global-keybindings cycle-panels-backward 'disabled'
org.mate.Marco.global-keybindings cycle-panels '<Control><Alt>Escape'
org.mate.Marco.global-keybindings cycle-windows '<Alt>Escape'
org.mate.Marco.global-keybindings cycle-windows-backward 'disabled'
org.mate.Marco.global-keybindings panel-main-menu '<Alt>F1'
org.mate.Marco.global-keybindings panel-run-dialog '<Alt>F2'
org.mate.Marco.global-keybindings rename-workspace 'disabled'
org.mate.Marco.global-keybindings run-command-10 'disabled'
org.mate.Marco.global-keybindings run-command-11 'disabled'
org.mate.Marco.global-keybindings run-command-12 'disabled'
org.mate.Marco.global-keybindings run-command-1 'disabled'
org.mate.Marco.global-keybindings run-command-2 'disabled'
org.mate.Marco.global-keybindings run-command-3 'disabled'
org.mate.Marco.global-keybindings run-command-4 'disabled'
org.mate.Marco.global-keybindings run-command-5 'disabled'
org.mate.Marco.global-keybindings run-command-6 'disabled'
org.mate.Marco.global-keybindings run-command-7 'disabled'
org.mate.Marco.global-keybindings run-command-8 'disabled'
org.mate.Marco.global-keybindings run-command-9 'disabled'
org.mate.Marco.global-keybindings run-command-screenshot 'Print'
org.mate.Marco.global-keybindings run-command-terminal 'disabled'
org.mate.Marco.global-keybindings run-command-window-screenshot '<Alt>Print'
org.mate.Marco.global-keybindings show-desktop '<Control><Alt>d'
org.mate.Marco.global-keybindings switch-group '<Alt>grave'
org.mate.Marco.global-keybindings switch-group-backward 'disabled'
org.mate.Marco.global-keybindings switch-panels-backward 'disabled'
org.mate.Marco.global-keybindings switch-panels '<Control><Alt>Tab'
org.mate.Marco.global-keybindings switch-to-workspace-10 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-11 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-12 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-1 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-2 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-3 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-4 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-5 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-6 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-7 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-8 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-9 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-down '<Control><Alt>Down'
org.mate.Marco.global-keybindings switch-to-workspace-left '<Control><Alt>Left'
org.mate.Marco.global-keybindings switch-to-workspace-prev 'disabled'
org.mate.Marco.global-keybindings switch-to-workspace-right '<Control><Alt>Right'
org.mate.Marco.global-keybindings switch-to-workspace-up '<Control><Alt>Up'
org.mate.Marco.global-keybindings switch-windows-all-backward 'disabled'
org.mate.Marco.global-keybindings switch-windows-all 'disabled'
org.mate.Marco.global-keybindings switch-windows '<Alt>Tab'
org.mate.Marco.global-keybindings switch-windows-backward 'disabled'
```
But it doesn`t make any different i set a few keys like yours.

Any ways, i it works for you all than ignore my comments, It must be a local problem.
....and i am getting more and more tired about problems which aren't mine after all that years with developing MATE.

**Comment by raveit65** [comment]
Dow !
I didn't realized that i have to hold down crt+alt and press the tab key again for switching to the panels.
I always pressed the whole crtl+alt+tab keybinding again.........
...so forget that noise, it works like a charm ;)

So, feel free to cherry-pick it to 1.20/18.

**Comment by vkareh** [comment]
LOL no worries - I was just booting up on Rawhide to see if I can help fix it, but it works fine here too - I'm glad you found out the issue on your side ;)

**Comment by vkareh** [comment]
@raveit65 - I cherry-picked it for both 1.20 and 1.18. That was weird, testing 1.18 on my HiDPI laptop :wink: but the fix applied cleanly and everything worked well

**Pull request merged**
