### PR TITLE
Allow use of arrows while in alt+tab popup

### PR DESCRIPTION
**Pull request by pldubouilh**
(issue #182)

### CODE REVIEW

**Comment by raveit65** [comment]
@pldubouilh 
We have a open question from core-team member.

**Comment by pldubouilh** [comment]
@monsta @raveit65 I added support for the numpad arrows too, but I don't have such a keyboard at hand so please test it

**Comment by raveit65** [comment]
I just tested it. Arrow keys on numpad are usable now.
Thank you

**Comment by monsta** [comment]
Works fine, but I accidentally noticed a funny thing...
You know that holding Shift in addition to Alt makes Tab switch the windows in reverse order. Guess what, now holding Shift swaps left and arrows too. 🙂 
Are you guys ok with that?

**Comment by raveit65** [comment]
The function of holding shift is to reverse something, so from logic point of view this is fine.
And i don't think that someone want to use the arrow keys and shift key at the same time.
We shouldn't make it more complicated with disabling the shift key if the arrow keys are used ;-)
I am OK with current state of PR.

**Comment by monsta** [comment]
> The function of holding shift is to reverse something, so from logic point of view this is fine.

I know, it's just funny how it affects arrow keys :slightly_smiling_face:

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/marco/commit/c4750c85961777e6ab00b46fb12b1ba0253796d5
https://github.com/mate-desktop/marco/commit/7c69bcf4d5b195902c770bcbf84bd8b8c3427059
Thank you

**Comment by raveit65** [comment]
@pldubouilh 
Don't forgot to claim the bounty here.
https://www.bountysource.com/issues/9539963-add-ability-to-use-the-arrow-keys-when-switching-windows-with-alt-tab

**Pull request closed without merging**
