### PR TITLE
compositor-xrender.c: keep tooltips visible in hidpi.

### PR DESCRIPTION
**Pull request by mtwebster**
Make sure tooltips are visible when the source widget is close to the edge of the work area. widget is close to the edge of the work area.

See inline comments - as of 3.24 tooltip positioning is handled
differently, and under certain conditions in hidpi, tooltips for the
bottom panel applets can end up off the bottom of the work area.

To reproduce, in hidpi, set the bottom panel to approximately 30px
tall and try to activate a tooltip for an applet on that panel.

- I'm not too familiar with this compositor, it's possible there's a better place for this sort of fix.
- I had assumed that since panels can be added to any monitor that I could get the precise work area for any monitor (not just for the primary) but that doesn't seem to be possible - tooltips will overlap the panel on a second monitor.

### CODE REVIEW

**Comment by muktupavels** [comment]
Sound like something that should be fixed in GTK...

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, and fixes 
https://github.com/mate-desktop/mate-panel/issues/1180
Tooltips render slightly high on a 4K monitor with a smaller secondary monitor attached but turned off, but that's a hell of a lot better than rendering them too low.

**Comment by lukefromdc** [comment]
Any updates on this?

**Comment by raveit65** [comment]
@vkareh 
Can you please do a review?
It runs fine since half a year at fedora stable all branches.
@lukefromdc 
No idea why Linuxmint head and Mate founder (Clement Lefebvre) do not  review his own developer from LM.
Any way, i am fine with merging it, because i didn't got any bugreport at RedHat Bugzilla with that commit.

**Comment by lukefromdc** [comment]
Should I wait to see if that review comes in or proceed to merge this?

**Pull request merged**
