### PR TITLE
Added hotkey to rename current workspace

### PR DESCRIPTION
**Pull request by fbarriga**
Add support for a hotkey that can rename the current workspace.

### CODE REVIEW

**Comment by raveit65** [comment]
Is there a reason why you bump version again in your PRs ?

**Comment by fbarriga** [comment]
@raveit65 bump version removed and branch rebased.

**Comment by monsta** [comment]
This looks quite complicated. Adding lots of code to launch zenity and handle its output... does this really belong to Marco?

**Comment by raveit65** [comment]
Any progress here?

**Comment by raveit65** [comment]
@fbarriga 
I like to see that feature in marco, but we have an open question here from a core-team member here?

**Comment by monsta** [comment]
I think it will be safe to close it for now.

**Comment by raveit65** [comment]
no, please do not, i like that feature!!

**Comment by monsta** [comment]
Ok, I just suggested :slightly_smiling_face:

**Comment by fbarriga** [comment]
@monsta I didn't like either have to use `zenity` for this but I didn't found any other solution. I decided to use it because it was the solution being used in function `meta_show_dialog`.

**Comment by raveit65** [comment]
Ok, that's declares it, i will  merge it the next days if nobody gives his veto ;-)
It works for me and i see no collateral damage.

**Comment by monsta** [comment]
Yes, zenity is used for showing a simple message dialog outside of marco's process, but there's no feedback like here (when some data is transferred from the dialog back to marco). I was wondering if it could possibly block marco's process or affect it in some other way.

**Comment by monsta** [comment]
For now it seems to work here. Maybe @lukefromdc could give it a try as well, just in case.

**Comment by lukefromdc** [comment]
I have never named my workspaces, to test this I would need to know how to undo that

**Comment by monsta** [comment]
Oh, that's easy: they're in `org.mate.Marco.workspace-names` schema, so you can just revert the keys to the default values if needed.

**Comment by raveit65** [comment]
@lukefromdc 
After renaming workspace 2 i get those gsettings value.
```
$ gsettings get org.mate.Marco.workspace-names name-2
'Sun of a .....'
```
With
```
$ gsettings reset org.mate.Marco.workspace-names name-2
```
i restore the default.

**Comment by raveit65** [comment]
opps, someone was faster :-)

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/marco/commit/5ded52f5e98d60abb903cc9194714a9b293ad482
Thank you.

**Comment by monsta** [comment]
No need to edit the schema, this new keybinding shows up in mate-keybinding-properties. :slightly_smiling_face: 

That said, maybe we should move it from Desktop to Window Management category? All workspace-related bindings are there.

**Pull request closed without merging**
