### PR TITLE
Implemented corner tiling

### PR DESCRIPTION
**Pull request by ozeidan**
Hi,
this is my attempt at implementing the corner tiling feature requested in issues #218. 
It works fairly well already when dragging the window with the mouse. I tried implementing the keyboard shortcuts for this but I didn't manage to understand how I can get the shortcuts to show up in gsettings. A little help on this would be appreciated.

### CODE REVIEW

**Comment by ozeidan** [comment]
So I managed to get the keybindings running. Here is a small preview:
corner-tiling
I will continue to look through the code once more because I am not sure if I am causing any side effects with this change.

**Comment by ozeidan** [comment]
@raveit65 I applied a quick fix for this, please try it out again. 

Currently, when a window is tiled into a corner it is maximized_vertically, which intuitively doesn't make much sense, but technically it seems to be the intended behaviour. Is that fine to leave in?

**Comment by ozeidan** [comment]
@lukefromdc I also noticed this behavior with Skype Preview, I'll try to fix this.

**Comment by lukefromdc** [comment]
I don't know what anyone else uses, but I have compiz setup to corner tile windows dragged to corners and ignore the top, bottom, left, and right edges entirely as far as tiling is concerned. It would seem to me that the only reason to use the corner as a target for dragging a window to tile it would be to tile the window quarter-screen from that corner.

**Comment by ozeidan** [comment]
@lukefromdc what are you trying to say? Isn't how you describe it the exact current behaviour? 

I am not able to 100% reproduce the bug with some windows not tiling to corners. Some hints to this would be appreciated.

**Comment by lukefromdc** [comment]
I normally do not use tiling with Marco at all because I move windows around a lot (and have jittery hands) and tiling any window on the edges acts in a way I find hard to control. The suggestion that windows should tile to halfscreen(maximized vertically) rather than quarterscreen on being dragged to a corner is what I was objecting to and could not understand being the intended behavior.

**Comment by raveit65** [comment]
I am pretty sure some users will point with the finger on it, if vertical resizing doesn't work.

The issue with dconf-editor i can't reproduce.
Here the preview and the tiling is working well, tested with f26 and dconf-editor-3.23.4-2.fc26.x86_64.
Same behaviour with other gnome apps like gnome-abrt, gnome-mpv, gitg.
The only issue i see with csd windows is that resizing a tiled window don't work.
But csd windows are using invisible borders for resizing and not a decorator edge,
This affects also our side-by-side-tiling, so this is a complete  other story and not related to PR.
I recall we have already a report about and it's save to ignore it for the moment, imo.

>  I normally do not use tiling with Marco at all because I move windows around a lot (and have jittery hands) and tiling any window on the edges acts in a way I find hard to control.

For me only the top edge is problematic because of the resizing to max window size, which can be a unwanted result if you move a window, especially with small notebook monitors.
But that's another story too :-)

**Comment by lukefromdc** [comment]
I am using an old version of deconf-editor (3.18) because I prefer its UI

**Comment by ozeidan** [comment]
Hi, so again I changed quite a few things. The resizing should work properly now. There might still be bugs, so please test as much as you can.

**Comment by vkareh** [comment]
Awesome - latest commit fixes the unmaximization issue for me - it works great!

I was wrong about the CSD windows - they tile just fine, except for `dconf-editor`, as @lukefromdc mentioned... not sure why that is, but everything else is behaving correctly.

Code looks good to me as well :)

**Comment by ozeidan** [comment]
I checked the issue with dconf-editor. It seems like the culprit is that the height of the size_hints of the dconf window is smaller than the height we want to resize it to when corner tiling. If I understand it correctly, those come from the application?

**Comment by raveit65** [comment]
@ozeidan 
Are you familiar with the 'git rebase command?
It looks like some commits can squashed together.
```
git rebase -i <last-good-commit>
```
-i means interactive and it opens an editor (vi), you will see how it works.
I think you know it better than me how much commits you need.

Btw. i don#t have the issue here with  dconf-editor-3.23.4-2.fc26.x86_64
So, i am thinking it's a problem with d-e-3.25

**Comment by raveit65** [comment]
@lukefromdc 
Do you like to test more?

**Comment by ozeidan** [comment]
@raveit65 So if my assumption is true, tiling dconf-editor (or other programs) may work on some screens but not on others. On bigger screens, the height of a 'corner' might be bigger than the minimum height that dconf-editor supplies. 

I renamed and squashed some commits on my local branch. Can I just force push them?

**Comment by raveit65** [comment]
@ozeidan 
yeah, i forgot to say. git push -f will update yor repo and the PR automatic

**Comment by raveit65** [comment]
@ozeidan 
You're right with dconf-editor. I works well on my my main box with a 27“ monitor, but not with the same rpm on my notebook with a (17,3“) Widescreen Display.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/marco/commit/b471b912d68a05711a95a3c0e033c0577262f18e
https://github.com/mate-desktop/marco/commit/8828bd7cabc39f0a3564467c2303774dc494fd0b
https://github.com/mate-desktop/marco/commit/01f68e8f9f1541393e6e069db08f834d4ef18691
https://github.com/mate-desktop/marco/commit/6219f8e8bcaeefb9185a3c3f5f20de4e2fa8f18f
https://github.com/mate-desktop/marco/commit/d8ef314fda4caf147162817bae4274910e9abc31
Thanks a lot for this feature.

**Pull request closed without merging**
