### PR TITLE
Fix losing title of windows with a 3 or 4 bytes first character

### LINKED ISSUE #757: Window title disappears when the first character is Chinese
#### Expected behaviour
Marco displays a window title starting with a character >= 3 bytes long.

#### Actual behaviour
Marco does not display a window title starting with a character >= 3 bytes long.

#### Steps to reproduce the behaviour
Open https://zh.wikipedia.org with firefox. The titlebar of firefox window does not contain a title.

#### MATE general version
1.26.1

#### Package version
marco 1.26.2

#### Linux Distribution
Debian

#### Link to bugreport of your Distribution (requirement)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041196

It seems that the fix for #749 caused this. Most Chinese characters are 3 bytes long under UTF-8, and UTF-8 characters can be as long as 4 bytes. So "g_utf8_strlen (title, 2) < 1" will be true if the first character is Chinese.

### PR DESCRIPTION
**Pull request by cwendling**
Fixes #757.

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Builds clean, and fixes the issue though with my fonts I only get the missing-character symbols. Without this the space stays entirely empty however, so this should confirm it works. Someone with the appropriate fonts installed ideally would also test this, but I doubt the characters themselves would change with this as opposed to whether they are displayed

**Comment by cwendling** [comment]
@lukefromdc it shouldn't change anything, but here I get proper characters (well, I see Chinese characters, and assume it's the right ones :)) and it works

**Comment by raveit65** [comment]
I have no idea what's wrong with https://zh.wikipedia.org/ on my fedora system. Chinese symbols are in the middle of the window title. Without a screenshot from reporter i would say it's debian specific :)

**Comment by raveit65** [comment]
I can confirm now the issue, sadly the bad commit is in latest 1.26. release.
I will test PR, but without a clear confirmation for PR from someone who use Chinese symbols, i don't like to do a new release for one commit to avoid breaking stable 1.26 branch again.

**Comment by cwendling** [comment]
@raveit65 hopefully @cloudfish will be able to test, but this is a very simple fix I am confident in.  If you confirm it fixes the Firefox example for you as well we should be good.  A maybe more important test is whether it doesn't break #749 -- but my tests with KCalc tell me it doesn't -- and the logic I see agrees.

**Review by raveit65 — APPROVED** [review]
Confirmed that it fixes the issue
and it doesn't break previous fix for running applications as superuser.

**Comment by raveit65** [comment]
If it is urgent Debian maintainer can use it as patch for his build.
Same what i do in fedora when it is urgent.
I like to test things a while before they go in stable.
Btw. everybody from the team can do new releases. This is not only in my hand ;)

**Comment by cwendling** [comment]
@mate-desktop/core-team can I cherry-pick this in 1.26?  We have the breaking change there, and it's affecting distros that might or might not know about it.

**Comment by cwendling** [comment]
Cherry-picked as a938884530839152c9854dd0d8248b36c3c2e3fd

**Pull request merged**
