### PR TITLE
theme-viewer: fix some deprecations

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by monsta** [comment]
Here's how it looks here with GTK+ 3.22.

Before:
theme-viewer-gtktable

After:
theme-viewer-gtkgrid

**Comment by monsta** [comment]
Also there are some new runtime warnings:

```
(marco-theme-viewer:19749): Gtk-WARNING **: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkToggleButton)

(marco-theme-viewer:19749): Gtk-WARNING **: Negative content height -10 (allocation 1, extents 5x6) while allocating gadget (node button, owner GtkToggleButton)

(marco-theme-viewer:19749): Gtk-WARNING **: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkToggleButton)

(marco-theme-viewer:19749): Gtk-WARNING **: Negative content height -10 (allocation 1, extents 5x6) while allocating gadget (node button, owner GtkToggleButton)
```

**Comment by raveit65** [comment]
I used gtk_widget_set_{h/v}expand to fix that.
Looks like that fixes aslo the runtime warnings.
...i did a forced push for that branch.

**Comment by raveit65** [comment]
..another forded push.
I found this commit in metacity.
https://mail.gnome.org/archives/commits-list/2014-June/msg00635.html
I think i will add more from there.

**Pull request merged**
