### PR TITLE
Avoiding conditional directives that break statements.

### PR DESCRIPTION
**Pull request by RomeroMalaquias**

### CODE REVIEW

**Comment by RomeroMalaquias** [comment]
Hello?

**Comment by raveit65** [comment]
Can you please describe a bit more what the commit does?
Btw., we are a small theme and it take some time to review all PRs.

**Comment by RomeroMalaquias** [comment]
Ok, sorry.
This change is only aesthetical, it's a suggestion based on code style guidelines from the Linux Kernel.
[Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)

**Comment by raveit65** [comment]
ok, i'm testing it

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/marco/commit/c6437bda0a9e7e26477c27fc355d9119b65d9d0d
Thank you

**Pull request closed without merging**
