### PR TITLE
Enable Clang Static Analyzer for marco

### PR DESCRIPTION
**Pull request by yetist**
The Travis document https://docs.travis-ci.com/user/deployment/#pull-requests said that:
>Pull Requests #
>Note that pull request builds skip the deployment step altogether.

Only commit can trigger the deploy, so create new branch for test.

@raveit65 

Can you set marco to use `gh-pages` branch as the page source?
That branch is ready: https://github.com/mate-desktop/marco/tree/gh-pages

### CODE REVIEW

**Comment by raveit65** [comment]
@yetist 
It is already enabled. I did nothing.....
bildschirmfoto zu 2019-02-22 13-58-55

**Comment by yetist** [comment]
Now http://mate-desktop.github.io/marco show 404, maybe should wait...

**Comment by raveit65** [comment]
Ok, i switched to master branch and back to gh-pages in drop-down-menu.
And now the page is there :)
This is a bit weird...

**Comment by sc0w** [comment]
@yetist Thanks!

how it works?

I noticed you pushed manually commits from  `travis` to `gh-pages` branch, or it was automatically by travis?

the page will be updated automatically in every opened PR? or when?

I like to understand the workflow :)

**Comment by yetist** [comment]
@sc0w 

This is automatically by travis, only commit event can update the page, skip PR.

The current workflow in travis is:

git clone->install packages->normal build->make distcheck # on other distros
git clone->install packages->normal build->[scan-build]->[create index.html]->make distcheck->[deploy html files] # on fedora distro

I think it's also possible to optimize the workflow like this, I will try:
git clone->install packages->scan-build->make distcheck # on other distros
git clone->install packages->scan-build->[create index.html]->make distcheck->[deploy html files] # on fedora

**Comment by yetist** [comment]
@rbuj @sc0w @raveit65 

Strange result, clang on debian can't build marco, https://travis-ci.org/mate-desktop/marco/builds/497355571
But it can build caja, https://travis-ci.org/mate-desktop/caja/builds/497356003

**Comment by rbuj** [comment]
@yetist 
remove --use-analyzer=/usr/bin/clang in
```
  - scan-build $CHECKERS --use-analyzer=/usr/bin/clang ./configure
  #- make clean
  - scan-build $CHECKERS --use-analyzer=/usr/bin/clang --keep-cc -o html-report make
```

**Comment by yetist** [comment]
@rbuj 

> Remove **--use-analyzer** argument.

Done, thank you.

**Comment by yetist** [comment]
Security issue found by clang analyzer. https://mate-desktop.github.io/marco

**Comment by lukefromdc** [comment]
That's quite a list of known problems found! Any chance of doing something like this for mate-panel, which is full of old memory leaks that I cannot find using Valgrind because there are too many? I have tried without succcess to find a redraw memory leak that is related to reports of the tray (or the clock with seconds enabled) causing a memory leak measured in GB when run over a week, but which I cannot duplicate locally.

**Comment by sc0w** [comment]
@lukefromdc you can use this `.sh` file to build mate-panel:

[clang.sh.zip](https://github.com/mate-desktop/marco/files/2897889/clang.sh.zip)

you need to install before in debian the packages `clang` and `clang-tools`

**Comment by lukefromdc** [comment]
I can't keep all those installed fulltime because its another 300+MB on disk and I ration the size of the root filesystem to simplify backup image handling. They have to go in, be used, and then be uninstalled.

**Comment by yetist** [comment]
Clang Analyzer results of f9b1e9d7fc34fe7cec99e1530b18babc3095f361 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of f9b1e9d7fc34fe7cec99e1530b18babc3095f361 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of f9b1e9d7fc34fe7cec99e1530b18babc3095f361 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of f9b1e9d7fc34fe7cec99e1530b18babc3095f361 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 08098949fe49fbce481c053b0dec78eb090abd25 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 08098949fe49fbce481c053b0dec78eb090abd25 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 08098949fe49fbce481c053b0dec78eb090abd25 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 08098949fe49fbce481c053b0dec78eb090abd25 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 7ce8b720268f933471df0adc8565233cefc6036c at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 7ce8b720268f933471df0adc8565233cefc6036c at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 7ce8b720268f933471df0adc8565233cefc6036c at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 7ce8b720268f933471df0adc8565233cefc6036c at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 6433e7e9bc554a73d757c8f3b0568518a380360f at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 6433e7e9bc554a73d757c8f3b0568518a380360f at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 6433e7e9bc554a73d757c8f3b0568518a380360f at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 6433e7e9bc554a73d757c8f3b0568518a380360f at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 31bd010adfe352959b27eac00932fc42a547fa6d at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Clang Analyzer results of 6ed76b7978ee935d379022fe4a566b4f538a394f at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
@lukefromdc 

> That's quite a list of known problems found! Any chance of doing something like this for mate-panel, which is full of old memory leaks that I cannot find using Valgrind because there are too many? I have tried without succcess to find a redraw memory leak that is related to reports of the tray (or the clock with seconds enabled) causing a memory leak measured in GB when run over a week, but which I cannot duplicate locally.

Done, see https://github.com/mate-desktop/mate-panel/pull/941

**Comment by lukefromdc** [comment]
Thanks

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of 39cc4a8ea6de08313a47140223f8cc527ee9c4d9 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of c1f7f4d59ccdc608eb5b2aa27ef1a5541590190e at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of f21c9bfe344fd27a8c67044418ab374e3844eb6e at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of b4a008c0ce94200009cd09d41d93037b2b64a74c at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of 11ee0e1fd9d966ce45661493719fc84585e354d5 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of 327d03741091140f7aff52abf4f067297278c698 at https://mate-desktop.github.io/marco/

**Comment by yetist** [comment]
Switch to use build scripts on master branch.

**Pull request merged**
