### PR TITLE
boxes: remove code duplication and add macros

### PR DESCRIPTION
**Pull request by rbuj**
Kept simple to read the code as well as reduce inner
function calls

### CODE REVIEW

**Comment by muktupavels** [comment]
What do you gain with this change? You make code less readable / understandable...

**Comment by sc0w** [comment]
I received this mail:

```
Hi,

in PR

https://github.com/mate-desktop/marco/pull/472/commits/1dbfcf5ac2ece2eef2fea91cab1a712ae1d30cd8

boxes: avoid code duplication and reduce number operations


in my mind the changes make the code more unreadable.

I suggest something like the following code ...

... snip ...
          /* If b contains a, just remove a */
          else if (meta_rectangle_contains_rect (b, a))
            {
              delete_me = compare;
            }
          /* If a and b both have same y and height,
           * they might be mergeable horizontally
           */
          else if (a->y == b->y && a->height == b->height)
            {
              /* If a and b horiz overlap or are horiz adjacent */
              if (meta_rectangle_horiz_overlap (a, b) ||
                  (a->x + a->width == b->x || a->x == b->x + b->width))
                {
                  int new_x = MIN (a->x, b->x);
                  a->width = MAX (a->x + a->width, b->x + b->width) - new_x;
                  a->x = new_x;
                  delete_me = other;
                }
            }
          /* If a and b both have same x and width,
           * they might be mergeable vertically
           */
          else if (a->x == b->x && a->width == b->width)
            {
              /* If a and b vert overlap or are vert adjacent */
              if (meta_rectangle_vert_overlap (a, b) ||
                  (a->y + a->height == b->y || a->y == b->y + b->height))
                {
                  int new_y = MIN (a->y, b->y);
                  a->height = MAX (a->y + a->height, b->y + b->height) - new_y;
                  a->y = new_y;
                  delete_me = other;
                }
            }

          other = other->next;
... snip ...

You could also add two functions, if you like :

gboolean
meta_rectangle_horiz_adjacent (const MetaRectangle *rect1,
                               const MetaRectangle *rect2)
{
  return (rect1->x + rect1->width == rect2->x ||
          rect2->x + rect2->width == rect1->x);
}

gboolean
meta_rectangle_vert_adjacent (const MetaRectangle *rect1,
                              const MetaRectangle *rect2)
{
  return (rect1->y + rect1->height == rect2->y ||
          rect2->y + rect2->height == rect1->y);
}

Then you could tweak the code a little :

-              /* If a and b horiz overlap or are horiz adjacent */
-              if (meta_rectangle_horiz_overlap (a, b) ||
-                  (a->x + a->width == b->x || a->x == b->x + b->width))
+              /* If a and b horiz overlap or are horiz adjacent */
+              if (meta_rectangle_horiz_overlap (a, b) ||
+                  meta_rectangle_horiz_adjacent (a, b))

and

-              /* If a and b vert overlap or are vert adjacent */
-              if (meta_rectangle_vert_overlap (a, b) ||
-                  (a->y + a->height == b->y || a->y == b->y + b->height))
+              /* If a and b vert overlap or are vert adjacent */
+              if (meta_rectangle_vert_overlap (a, b) ||
+                  meta_rectangle_vert_adjacent (a, b))

With or without the two added functions the current code is
improved by removing duplicated code and kept simple to read.

Regards,

Juha from Kuopio, Finland
```

**Comment by rbuj** [comment]
@sc0w 
Ok, I will send the change to see what is the most suitable for the compression of the code.

**Comment by raveit65** [comment]
Can we close this?
@vkareh 
What do you think?

**Comment by vkareh** [comment]
A lot of this doesn't make sense to change. For example,
```diff
+ #define META_RECTANGLE_CONTAINS_RECTANGLE(OUTER_RECT, INNER_RECT)                  \
+  ((INNER_RECT->x                        >= OUTER_RECT->x) &&                       \
+   (INNER_RECT->y                        >= OUTER_RECT->y) &&                       \
+   ((INNER_RECT->x + INNER_RECT->width)  <= (OUTER_RECT->x + OUTER_RECT->width)) && \
+   ((INNER_RECT->y + INNER_RECT->height) <= (OUTER_RECT->y + OUTER_RECT->height)))

gboolean
meta_rectangle_contains_rect  (const MetaRectangle *outer_rect,
                               const MetaRectangle *inner_rect)
{
-  return
-    inner_rect->x                      >= outer_rect->x &&
-    inner_rect->y                      >= outer_rect->y &&
-    inner_rect->x + inner_rect->width  <= outer_rect->x + outer_rect->width &&
-    inner_rect->y + inner_rect->height <= outer_rect->y + outer_rect->height;
+  return META_RECTANGLE_CONTAINS_RECTANGLE (outer_rect, inner_rect);
}
```
This replaces an existing function with a macro, reusing the function to return the macro. It's less readable, harder to follow the code flow, and unnecessary. Why?

**Pull request closed without merging**
